---
title: "Calculate correlations polarization measurements"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(number_sections = FALSE)
options(width = 100)
colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```


In this script I calculate the correlations between our chosen measure of polarization (variance) and a bimodal measure

```{r}
rm(list=ls())
library(tidyverse)
library(dplyr)
library(gamlss)
library(multimode)
```

I'm going to compare some random waves, not all attitudes. 
```{r}
# Take the sigma and the excess mass from the first attitude of four datasets. 
load("./data/final_data/regression_outputs/ess_list_empty_w.RData") 
sum_ess <- summary(ess_list_empty[[1]])   # Dit miss nog subsetten op jaar                  
  sigma_ess <- sum_ess[[3]]
  
load("./data/final_data/esstotal.RData")
ess_complete <- esstotal %>% drop_na()
ess_complete$time <- ess_complete$surveyyear - min(ess_complete$surveyyear)  
residuals_ess <- ess_list_empty[[1]]$residuals
excess_mass_ess_t1 <- modetest(residuals_ess[ess_complete$time == 0])  
excess_mass_ess_t1 <- excess_mass_ess_t1$statistic
excess_mass_ess_t2 <- modetest(residuals_ess[ess_complete$time == 4]) 
excess_mass_ess_t2 <- excess_mass_ess_t2$statistic

# Now the same for another dataset
load("./data/final_data/regression_outputs/evs_list_empty_w.RData") 
sum_evs <- summary(evs_list_empty[[1]])

  sigma_evs <- sum_evs[[3]]
  
load("./data/final_data/evssel.RData")
evs_complete <- evssel %>% drop_na()
evs_complete$time <- evs_complete$surveyyear - min(evs_complete$surveyyear)
table(evs_complete$time)
residuals_evs <- evs_list_empty[[1]]$residuals
excess_mass_evs_t1 <- modetest(residuals_evs[evs_complete$time == 0])  
excess_mass_evs_t1 <- excess_mass_evs_t1$statistic
excess_mass_evs_t2 <- modetest(residuals_evs[evs_complete$time == 18]) 
excess_mass_evs_t2 <- excess_mass_evs_t2$statistic


# And another one
load("./data/final_data/regression_outputs/mot_list_empty_w.RData") 
sum_mot <- summary(mot_list_empty[[1]])
sigma_mot <- sum_mot[[3]]
  
load("./data/final_data/mottotal.RData")
mot_complete <- mottotal %>% drop_na()
mot_complete$time <- mot_complete$surveyyear - min(mot_complete$surveyyear)
table(mot_complete$time)
residuals_mot <- evs_list_empty[[1]]$residuals
excess_mass_mot_t1 <- modetest(residuals_mot[mot_complete$time == 0])  
excess_mass_mot_t1 <- excess_mass_mot_t1$statistic
excess_mass_mot_t2 <- modetest(residuals_mot[mot_complete$time == 2]) 
excess_mass_mot_t2 <- excess_mass_mot_t2$statistic

#And another dataset 
load("./data/final_data/regression_outputs/liss_list_empty_w.RData") 
sum_liss <- summary(liss_list_empty[[1]])

  sigma_liss <- sum_liss[[3]]
  
load("./data/final_data/lisstotal.RData")
liss_complete <- lisstotal %>% drop_na()
liss_complete$time <- liss_complete$surveyyear - min(liss_complete$surveyyear)
table(liss_complete$time)
residuals_liss <- liss_list_empty[[1]]$residuals
excess_mass_liss_t1 <- modetest(residuals_liss[liss_complete$time == 0])  
excess_mass_liss_t1 <- excess_mass_liss_t1$statistic
excess_mass_liss_t2 <- modetest(residuals_liss[liss_complete$time == 2]) 
excess_mass_liss_t2 <- excess_mass_liss_t2$statistic


# Let's try to make a dataset out of these scores. 
dataset <- c("ESS", "EVS", "MOT", "LISS")
sigma <- c(sigma_ess, sigma_evs, sigma_mot, sigma_liss)
excess_mass_t1 <- c(excess_mass_ess_t1, excess_mass_evs_t1, excess_mass_mot_t1, excess_mass_liss_t1)
excess_mass_t2 <- c(excess_mass_ess_t2, excess_mass_evs_t2, excess_mass_mot_t2, excess_mass_liss_t2)

cor_pol <- data.frame(dataset, sigma, excess_mass_t1, excess_mass_t2)
# As sigma is measured over time, I want to correlate this to the increase or decrease of the excess mass over the same time span. 
cor_pol$excess_mass_diff <- cor_pol$excess_mass_t2 - cor_pol$excess_mass_t1

# And calculate the correlation
cor <- cor(cor_pol$sigma, cor_pol$excess_mass_diff)
# Correlation of -0.755, so very high
```


```{r}
# Done in meeting
residuals <- ess_fit$residuals
table(residuals)
install.packages("multimode")
library(multimode)
table(ess_complete$time)
modetest(residuals[ess_complete$time == 0])
modetest(residuals[ess_complete$time == 4])

var(residuals[ess_complete$time == 0])
var(residuals[ess_complete$time == 4])


residuals2 <- ess_list_empty[[1]]$residuals
modetest(residuals2[ess_complete$time == 0])
modetest(residuals2[ess_complete$time == 4])

(var(residuals2[ess_complete$time == 0]))^2
var(residuals2[ess_complete$time == 4])

t1 <- lm(worry ~ time, data=ess_complete)
summary(t1)

nmodes(residuals, bw=0.5)


```

