---
title: "Untitled"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
rm(list = ls())
#library(haven)
library(plyr)
library(dplyr)
library(foreign)
library(tidyverse)
library(labelled)
library(ggplot2)
library(questionr)
library(psych)

```

```{r}
#Now the biggest project of all: the Eurobarometer. 
eb1982 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb1982.sav", use.value.labels = T,  to.data.frame = T)

eb1982sel <- eb1982 %>% filter(v5=="NETHERLANDS") %>%
            select(v1, v4, v7, v8, v31, v51, v52, v53, v62, v66, v67, v71, v72, v74, v82) 

attributes(eb1982sel$v31)
table(eb1982sel$v31, useNA = "always")
eb1982sel$v31 <- as.numeric(eb1982sel$v31)
eb1982sel$v31[is.na(eb1982sel$v31)] <- 88
eb1982sel$v31 <- as.factor(eb1982sel$v31)
levels(eb1982sel$v31) <- c("Statement A", "Statement B", "Other", "Missing")
table(eb1982sel$v51, useNA = "always")
eb1982sel$v51 <- as.numeric(eb1982sel$v51)
eb1982sel$v51[is.na(eb1982sel$v51)] <- 88
table(eb1982sel$v52, useNA = "always")
eb1982sel$v52 <- as.numeric(eb1982sel$v52)
eb1982sel$v52[is.na(eb1982sel$v52)] <- 88
eb1982sel$v52 <- as.factor(eb1982sel$v52)
levels(eb1982sel$v52) <- c("Very close", "Fairly close", "Merely sympthasis", "Close to no party", "Missing")
table(eb1982sel$v53, useNA = "always")
eb1982sel$v53 <- as.numeric(eb1982sel$v53)
eb1982sel$v53[is.na(eb1982sel$v53)] <- 88
eb1982sel$v53 <- as.factor(eb1982sel$v53)
levels(eb1982sel$v53) <- c("Religious", "Not religious", "Atheist", "Missing")
table(eb1982sel$v62, useNA = "always") #No missings on education
table(eb1982sel$v66, useNA = "always") #No missings on gender
table(eb1982sel$v67, useNA = "always") #25 missings on age. Substitute. 
table(eb1982sel$v71, useNA = "always") #Income 105 missings
table(eb1982sel$v72, useNA = "always") #Same for cats
table(eb1982sel$v74, useNA = "always") #Same missings as income cats
table(eb1982sel$v82, useNA = "always") #25 missings on community size
eb1982sel$v82 <- as.numeric(eb1982sel$v82)
eb1982sel$v82[is.na(eb1982sel$v82)] <- 88
eb1982sel$v82 <- as.factor(eb1982sel$v82)
levels(eb1982sel$v82) <- c("Rural area-vilage", "Mid size town", "Big town", "Missing")

eb1982sel$v67 <- as.numeric(eb1982sel$v67)
mean(eb1982sel$v67, na.rm = T)
eb1982sel$v67[is.na(eb1982sel$v67)] <- 41.51891

eb1982sel$v71 <- as.numeric(eb1982sel$v71)             
mean(eb1982sel$v71, na.rm = T)
eb1982sel$v71[is.na(eb1982sel$v71)] <- 6.719243

#For age and income cat there are still missings. Decide later what I do with that. 

save(eb1982sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb1982sel.Rdata")

#Next 1986.
eb1986 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb1986.sav", use.value.labels = T,  to.data.frame = T)

eb1986sel <- eb1986 %>% filter(v5=="NETHERLANDS") %>%
            select(v1, v4, v8, v9, v218, v161, v270, v280, v281, v284, v290, v291, v296, v302, v303)

attributes(eb1986sel$v161)
attributes(eb1986sel$v218)
                   
table(eb1986sel$v161, useNA = "always") #19 missings. Have to recode bc now a low score means that it's not really a problem. 
eb1986sel$v161 <- as.numeric(eb1986sel$v161)
eb1986sel$problem_r[eb1986sel$v161==1] <- 3
eb1986sel$problem_r[eb1986sel$v161==2] <- 2
eb1986sel$problem_r[eb1986sel$v161==3] <- 1
table(eb1986sel$problem_r, useNA = "always")
table(eb1986sel$v218, useNA = "always") #60 missings. 1 means development of economy is more important than environment, 3 means protecting environment are necessary for economic development --> higher score thus more positive. 
table(eb1986sel$v270, useNA = "always") #55 missings on rl placement. Numeric: highest score is most right. 
eb1986sel$v270 <- as.numeric(eb1986sel$v270)
eb1986sel$v270[is.na(eb1986sel$v270)] <- 88
table(eb1986sel$v280, useNA = "always") #23 missings on party sympathis
eb1986sel$v280 <- as.numeric(eb1986sel$v280)
eb1986sel$v280[is.na(eb1986sel$v280)] <- 88
eb1986sel$v280 <- as.factor(eb1986sel$v280)
levels(eb1986sel$v280) <- c("Very close", "Fairly close", "Merely sympthasis", "Close to no party", "Missing")
table(eb1986sel$v281, useNA = "always") #15 missings on religion. 
eb1986sel$v281 <- as.numeric(eb1986sel$v281)
eb1986sel$v281[is.na(eb1986sel$v281)] <- 88 #High score means very religious.
table(eb1986sel$v284, useNA = "always") #No missings education. 
table(eb1986sel$v290, useNA = "always") #No missings on gender
table(eb1986sel$v291, useNA = "always") #No missings on age. 
table(eb1986sel$v296, useNA = "always") #159 missings income. 
eb1986sel$v296 <- as.numeric(eb1986sel$v296)
mean(eb1986sel$v296, na.rm=T)
eb1986sel$v296[is.na(eb1986sel$v296)] <- 7.048694
table(eb1986sel$v302, useNA = "always") #no missings on community
table(eb1986sel$v303, useNA = "always") #Logically same nr of missings on income cat. 

save(eb1986sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb1986sel.Rdata")

#1988
eb1988 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb1988.sav", use.value.labels = T,  to.data.frame = T)

#For some reason the selecting does not work??? On 2nd try neither. Works with resp id. But now I get an error when I want to select the variables
eb1988sel <- eb1988 %>% filter(v4>=8055 & v4 <= 9077) 
     select(v1, v6, v221, v170, v420, v415, v426, v427, v432, v438)

     
look_for (eb1988sel, "education")
     
#Continue with 1992
eb1992 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb1992.sav", use.value.labels = T,  to.data.frame = T)

eb1992sel <- eb1992 %>% filter(v5=="NETHERLANDS") %>%
  select(v1, v8, v9, v456, v449, v645, v648, v649, v650, v601, v602, v611, v615, v616)

attributes(eb1992sel$v456) #Higher score means environment priority. 
attributes(eb1992sel$v449) #After recode --> higher score means more of a problem. 
eb1992sel$v449 <- as.numeric(eb1992sel$v449)
eb1992sel$problem_r[eb1992sel$v449==1] <- 3
eb1992sel$problem_r[eb1992sel$v449==2] <- 2
eb1992sel$problem_r[eb1992sel$v449==3] <- 1
table(eb1992sel$problem_r, useNA = "always")
table(eb1992sel$v449, useNA = "always")
table(eb1992sel$v645, useNA = "always") #9 missings on urbanity. 
eb1992sel$v645 <- as.numeric(eb1992sel$v645)
eb1992sel$v645[is.na(eb1992sel$v645)] <- 88
eb1992sel$v645 <- as.factor(eb1992sel$v645)
levels(eb1992sel$v645) <- c("Rural area-vilage", "Mid size town", "Big town", "Missing")
table(eb1992sel$v648, useNA = "always") #Religion has 77 missings. But I notice that answer cats differ over the years. 
eb1992sel$v648 <- as.numeric(eb1992sel$v648)
eb1992sel$v648[is.na(eb1992sel$v648)] <- 88
eb1992sel$v648 <- as.factor(eb1992sel$v648)
levels(eb1992sel$v648) <- c("Religious", "Not religious", "Agnost", "Atheist", "Missing")
table(eb1992sel$v649, useNA = "always") #Income has 143 missings
eb1992sel$v649 <- as.numeric(eb1992sel$v649)
mean(eb1992sel$v649, na.rm=T)
eb1992sel$v649[is.na(eb1992sel$v649)] <- 7.427241
table(eb1992sel$v601, useNA = "always") #78 missings on left right placement. 
eb1992sel$v601 <- as.numeric(eb1992sel$v601)
eb1992sel$v601[is.na(eb1992sel$v601)] <- 88
table(eb1992sel$v602, useNA = "always") #Also in cats, so not necessary. 
table(eb1992sel$v611, useNA = "always") #No missings on education
table(eb1992sel$v615, useNA = "always")#No missings gender
table(eb1992sel$v616, useNA = "always") #No missings on age

save(eb1992sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb1992sel.Rdata")

#1995
eb1995 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb1995.sav", use.value.labels = T,  to.data.frame = T)

eb1995sel <- eb1995 %>% filter(v5=="Netherlands") %>%
  select(v1, v8, v9, v182, v134, v339, v343, v344, v345, v354, v355)

attributes(eb1995sel$v182) #Higher score means environment higher priority. 
attributes(eb1995sel$v134)
table(eb1995sel$v134, useNA = "always")
eb1995sel$v134 <- as.numeric(eb1995sel$v134)
eb1995sel$problem_r[eb1995sel$v134==1] <- 3
eb1995sel$problem_r[eb1995sel$v134==2] <- 2
eb1995sel$problem_r[eb1995sel$v134==3] <- 1
table(eb1995sel$problem_r, useNA = "always")
table(eb1995sel$v339, useNA = "always") #90 missings on lr placement
eb1995sel$v339 <- as.numeric(eb1995sel$v339)
eb1995sel$v339[is.na(eb1995sel$v339)] <- 88
table(eb1995sel$v343, useNA = "always") #No missings education
table(eb1995sel$v344, useNA = "always") #No missings gender
table(eb1995sel$v345, useNA = "always") #No missings age
table(eb1995sel$v354, useNA = "always") #No missings urbanity
table(eb1995sel$v355, useNA = "always") #199 missings  income
eb1995sel$v355 <- as.numeric(eb1995sel$v355)
mean(eb1995sel$v355, na.rm = T)
eb1995sel$v355[is.na(eb1995sel$v355)] <- 6.831271

save(eb1995sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb1995sel.Rdata")

#1999
eb1999 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb1999.sav", use.value.labels = T,  to.data.frame = T)

eb1999sel <- eb1999 %>% filter(v6=="The Netherlands") %>%
  select(v1, v9,v10, v190, v735, v737, v738, v752, v767, v776, v791)

attributes(eb1999sel$v190) #Environmental protection should also take economic and social effects into account. 
table(eb1999sel$v735, useNA = "always") #86 missins on educyrs
eb1999sel$v735 <- as.numeric(eb1999sel$v735)
mean(eb1999sel$v735, na.rm=T)
eb1999sel$v735[is.na(eb1999sel$v735)] <- 9.607182
table(eb1999sel$v737, useNA = "always") #No missings gender
table(eb1999sel$v738, useNA = "always") #No missings age
table(eb1999sel$v752, useNA = "always") #155 missings income in gulden
table(eb1999sel$v767, useNA = "always") #i think i should use this var, as it is coded the same as the other waves. Also 155 missings. 
eb1999sel$v767 <- as.numeric(eb1999sel$v767)
mean(eb1999sel$v767, na.rm=T)
eb1999sel$v767[is.na(eb1999sel$v767)] <- 7.758824
table(eb1999sel$v791, useNA = "always") #No missings on urbanity
table(eb1999sel$v776, useNA = "always") #No missings on urbanity. This one is coded in groups of number of inhabitants. So they changed this. 

save(eb1999sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb1999sel.Rdata")

#2004
eb2004 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2004.sav", use.value.labels = T,  to.data.frame = T)

look_for (eb2004, "age")

eb2004sel <- eb2004 %>% filter(v6=="The Netherlands") %>%
  select(v1, v8, v307, v308, v309, v310, v312, v579, v583, v585, v586, v58)

#Miss iets maken waarmee v307 hoger moet zijn dan v308 en 309 ofzo, want dan is het klimaat belangrijker. 
#Deze wave heeft geen inkomen??

attributes(eb2004sel$v310)
attributes(eb2004sel$v307) #Environment a problem? 
eb2004sel$v307 <- as.numeric(eb2004sel$v307)
eb2004sel$v307_r[eb2004sel$v307==1] <- 4
eb2004sel$v307_r[eb2004sel$v307==2] <- 3
eb2004sel$v307_r[eb2004sel$v307==3] <- 2
eb2004sel$v307_r[eb2004sel$v307==4] <- 1
table(eb2004sel$v307, useNA = "always")

attributes(eb2004sel$v312)
eb2004sel$v312 <- as.numeric(eb2004sel$v312)
eb2004sel$v312_r[eb2004sel$v312==1] <- 4
eb2004sel$v312_r[eb2004sel$v312==2] <- 3
eb2004sel$v312_r[eb2004sel$v312==3] <- 2
eb2004sel$v312_r[eb2004sel$v312==4] <- 1
table(eb2004sel$v312, useNA = "always")

table(eb2004sel$v579, useNA = "always") #54 missings on left-right placement. 
eb2004sel$v579 <- as.numeric(eb2004sel$v579)
mean(eb2004sel$v579, na.rm = T)
eb2004sel$v579[is.na(eb2004sel$v579)] <- 5.089864
table(eb2004sel$v583, useNA = "always") #8 missings on education. 
eb2004sel$v583 <- as.numeric(eb2004sel$v583)
freq(eb2004sel$v583)
eb2004sel$v583[is.na(eb2004sel$v583)] <- 88
eb2004sel$v583 <- as.factor(eb2004sel$v583)
table(eb2004sel$v585, useNA = "always") #No missings gender
table(eb2004sel$v586, useNA = "always") #No missings on urbanity
table(eb2004sel$v58, useNA = "always") #No missings on age


save(eb2004sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2004sel.Rdata")
```


```{r}
eb2007 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2007.sav", use.value.labels = T,  to.data.frame = T)

eb2007sel <- eb2007 %>% filter(v6=="The Netherlands") %>%
  select(v1, v8, v548, v543, v544, v592, v593, v594, v549, v474, v612, v616, v618, v619, v624)

attributes(eb2007sel$v548) #Recode. Now a higher score means that environment has priority over economic competitiveness.
eb2007sel$v548 <- as.numeric(eb2007sel$v548)
eb2007sel$v548_r <- NA
eb2007sel$v548_r[eb2007sel$v548==1] <- 2 
eb2007sel$v548_r[eb2007sel$v548==2] <- 1
table(eb2007sel$v548, useNA = "always")

attributes(eb2007sel$v543) #Progress should be measured based on economic indicators and social and environmental indicators. Score 2 means that you indeed want that.
attributes(eb2007sel$v544) #Influence on daily life. Recode. 
eb2007sel$v544 <- as.numeric(eb2007sel$v544)
eb2007sel$v544_r[eb2007sel$v544==1] <- 4
eb2007sel$v544_r[eb2007sel$v544==2] <- 3
eb2007sel$v544_r[eb2007sel$v544==3] <- 2
eb2007sel$v544_r[eb2007sel$v544==4] <- 1
table(eb2007sel$v544_r, useNA = "always")
table(eb2007sel$v544, useNA = "always")
attributes(eb2007sel$v592) #As an individual, you can play a role in protecting the environment. 
eb2007sel$v592 <- as.numeric(eb2007sel$v592)
eb2007sel$v592_r[eb2007sel$v592==1] <- 4
eb2007sel$v592_r[eb2007sel$v592==2] <- 3
eb2007sel$v592_r[eb2007sel$v592==3] <- 2
eb2007sel$v592_r[eb2007sel$v592==4] <- 1
table(eb2007sel$v592_r, useNA = "always")
table(eb2007sel$v592, useNA = "always") #Higher score means that you agree
attributes(eb2007sel$v593) #The big polluters should be mainly responsible. Difficult how to code this, but I interpret it as follows: when you want to hold someone responsible you at least think it's important that something should be done. So if one agrees more, one has more positive attitudes. 
eb2007sel$v593 <- as.numeric(eb2007sel$v593)
eb2007sel$v593_r[eb2007sel$v593==1] <- 4
eb2007sel$v593_r[eb2007sel$v593==2] <- 3
eb2007sel$v593_r[eb2007sel$v593==3] <- 2
eb2007sel$v593_r[eb2007sel$v593==4] <- 1
table(eb2007sel$v593_r, useNA = "always")
table(eb2007sel$v593, useNA = "always")
attributes(eb2007sel$v594) #Environmental issues have a direct effect on daily life. Recode so that higher code means you agree more. 
eb2007sel$v594 <- as.numeric(eb2007sel$v594)
eb2007sel$v594_r[eb2007sel$v594==1] <- 4
eb2007sel$v594_r[eb2007sel$v594==2] <- 3
eb2007sel$v594_r[eb2007sel$v594==3] <- 2
eb2007sel$v594_r[eb2007sel$v594==4] <- 1
table(eb2007sel$v594_r, useNA = "always")
table(eb2007sel$v594, useNA = "always")
attributes(eb2007sel$v549) #Willing to buy more environmental friendly products.
eb2007sel$v549 <- as.numeric(eb2007sel$v549)
eb2007sel$v549_r[eb2007sel$v549==1] <- 4
eb2007sel$v549_r[eb2007sel$v549==2] <- 3
eb2007sel$v549_r[eb2007sel$v549==3] <- 2
eb2007sel$v549_r[eb2007sel$v549==4] <- 1
table(eb2007sel$v549_r, useNA = "always")
table(eb2007sel$v549, useNA = "always")
attributes(eb2007sel$v474) #Protecting the environment important personally. 
eb2007sel$v474 <- as.numeric(eb2007sel$v474)
eb2007sel$v474_r[eb2007sel$v474==1] <- 4
eb2007sel$v474_r[eb2007sel$v474==2] <- 3
eb2007sel$v474_r[eb2007sel$v474==3] <- 2
eb2007sel$v474_r[eb2007sel$v474==4] <- 1
table(eb2007sel$v474_r, useNA = "always")
table(eb2007sel$v474, useNA = "always")

table(eb2007sel$v612, useNA = "always") #45 missings on l-r placement. Replace with mean. 
eb2007sel$v612 <- as.numeric(eb2007sel$v612)
mean(eb2007sel$v612, na.rm=T)
eb2007sel$v612[is.na(eb2007sel$v612)] <- 5.093194
table(eb2007sel$v616, useNA = "always") #8 missings on educyrs. 
eb2007sel$v616 <- as.numeric(eb2007sel$v616)
freq(eb2007sel$v616)
eb2007sel$v616[is.na(eb2007sel$v616)] <- 88
table(eb2007sel$v618, useNA = "always") #No  missings on gender. 
table(eb2007sel$v619, useNA = "always") #No missings on age. 
table(eb2007sel$v624, useNA = "always") #No missings on urbanity. 

save(eb2007sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2007sel.Rdata")
```


```{r}
#2008
eb2008 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2008.sav", use.value.labels = T,  to.data.frame = T)

eb2008sel <- eb2008 %>% filter(v6=="The Netherlands") %>%
  select(v1, v8, v553, v554, v647, v725, v705, v720, v721, v722, v723, v724, v761, v765, v767, v768, v773)

attributes(eb2008sel$v553) #Split ballot met v554. Misschien hercoderen dat ze elkaar aanvullen. 
attributes(eb2008sel$v647[1])
eb2008sel$gwarming <- NA
eb2008sel$v647 <- as.numeric(eb2008sel$v647)
eb2008sel$gwarming[eb2008sel$v647==1] <- 1
eb2008sel$gwarming[eb2008sel$v647!=1] <- 0
table(eb2008sel$v647, useNA = "always")
table(eb2008sel$gwarming, useNA = "always") #534 missings on most important problem --> maybe not so useful. 
attributes(eb2008sel$v725) #I have personally taken action to fight climate change. 
eb2008sel$v725 <- as.numeric(eb2008sel$v725)
eb2008sel$v725_r[eb2008sel$v725==1] <- 4
eb2008sel$v725_r[eb2008sel$v725==2] <- 3
eb2008sel$v725_r[eb2008sel$v725==3] <- 2
eb2008sel$v725_r[eb2008sel$v725==4] <- 1
table(eb2008sel$v725_r, useNA = "always")
table(eb2008sel$v725, useNA = "always")
attributes(eb2008sel$v705) #Perception of climate change as problem. Coded right way --> higher score more serious problem
table(eb2008sel$v705, useNA = "always") #But 515 missings
attributes(eb2008sel$v720) #Climate change is an unstoppable process. Difficult, bc even if you believe in it/are concerned you may think it's unstoppable. For now ill code it as more agreeness --> more positive
eb2008sel$v720 <- as.numeric(eb2008sel$v720)
eb2008sel$v720_r[eb2008sel$v720==1] <- 4
eb2008sel$v720_r[eb2008sel$v720==2] <- 3
eb2008sel$v720_r[eb2008sel$v720==3] <- 2
eb2008sel$v720_r[eb2008sel$v720==4] <- 1
table(eb2008sel$v720_r, useNA = "always")
table(eb2008sel$v720, useNA = "always")
attributes(eb2008sel$v721) #Seriousness is exaggerated. If you disagree, you have more positive attitudes. 
eb2008sel$v721 <- as.numeric(eb2008sel$v721)
attributes(eb2008sel$v722) #CO2 has marginal impact. This expresses more knowledge than concern I think. Not sure whether I should use that one. But maybe if you disagree more you know that it has a large impact (but still knowledge)
eb2008sel$v722 <- as.numeric(eb2008sel$v722)
attributes(eb2008sel$v723) #Fighting climate change has positive impact on EU. Again, can't simply divide that into more positive. You may still think climate change is important and that it does not matter that it has a negative impact on the economy. For now I recode it, because then it means that you at least don't think the economy is an obstacle in fighting climate change. 
eb2008sel$v723 <- as.numeric(eb2008sel$v723)
eb2008sel$v723_r[eb2008sel$v723==1] <- 4
eb2008sel$v723_r[eb2008sel$v723==2] <- 3
eb2008sel$v723_r[eb2008sel$v723==3] <- 2
eb2008sel$v723_r[eb2008sel$v723==4] <- 1
table(eb2008sel$v723_r, useNA = "always")
table(eb2008sel$v723, useNA = "always")
attributes(eb2008sel$v724) #We should use alternative fuels. If you agree with this you at least have thought about alternative ways and think change is needed. 
eb2008sel$v724 <- as.numeric(eb2008sel$v724)
eb2008sel$v724_r[eb2008sel$v724==1] <- 4
eb2008sel$v724_r[eb2008sel$v724==2] <- 3
eb2008sel$v724_r[eb2008sel$v724==3] <- 2
eb2008sel$v724_r[eb2008sel$v724==4] <- 1
table(eb2008sel$v724_r, useNA = "always")
table(eb2008sel$v724, useNA = "always")

table(eb2008sel$v761, useNA = "always") #41 missings on l-r placement. 
eb2008sel$v761 <- as.numeric(eb2008sel$v761)
mean(eb2008sel$v761, na.rm=T)
eb2008sel$v761[is.na(eb2008sel$v761)] <- 5.222
table(eb2008sel$v765, useNA = "always") #2 missings on education years. 
eb2008sel$v765 <- as.numeric(eb2008sel$v765)
freq(eb2008sel$v765)
eb2008sel$v765[is.na(eb2008sel$v765)] <- 88
table(eb2008sel$v767, useNA = "always") #Gender no missings
table(eb2008sel$v768, useNA = "always") #Age neither
table(eb2008sel$v773, useNA = "always") #Urbanity neither. 

save(eb2008sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2008sel.Rdata")
```


```{r}
#2009 (2 datasets)
eb2009_1 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2009_1.sav", use.value.labels = T,  to.data.frame = T)

eb2009asel <- eb2009_1 %>% filter(v6=="The Netherlands") %>%
  select(v1, v8, v129, v522, v526, v527, v528, v529, v530, v531, v145, v638, v642, v644, v645, v650)

attributes(eb2009asel$v129) #Environmental protection is important country issue. 2 = mentioned
eb2009asel$v129 <- as.numeric(eb2009asel$v129)
attributes(eb2009asel$v526)
eb2009asel$v526 <- as.numeric(eb2009asel$v526)
eb2009asel$v526_r[eb2009asel$v526==1] <- 4
eb2009asel$v526_r[eb2009asel$v526==2] <- 3
eb2009asel$v526_r[eb2009asel$v526==3] <- 2
eb2009asel$v526_r[eb2009asel$v526==4] <- 1
table(eb2009asel$v526_r, useNA = "always")
table(eb2009asel$v526, useNA = "always")
eb2009asel$v527 <- as.numeric(eb2009asel$v527)
eb2009asel$v528 <- as.numeric(eb2009asel$v528)
eb2009asel$v529 <- as.numeric(eb2009asel$v529)
eb2009asel$v529_r[eb2009asel$v529==1] <- 4
eb2009asel$v529_r[eb2009asel$v529==2] <- 3
eb2009asel$v529_r[eb2009asel$v529==3] <- 2
eb2009asel$v529_r[eb2009asel$v529==4] <- 1
table(eb2009asel$v529_r, useNA = "always")
table(eb2009asel$v529, useNA = "always")

eb2009asel$v530 <- as.numeric(eb2009asel$v530)
eb2009asel$v530_r[eb2009asel$v530==1] <- 4
eb2009asel$v530_r[eb2009asel$v530==2] <- 3
eb2009asel$v530_r[eb2009asel$v530==3] <- 2
eb2009asel$v530_r[eb2009asel$v530==4] <- 1
table(eb2009asel$v530_r, useNA = "always")
table(eb2009asel$v530, useNA = "always")

attributes(eb2009asel$v531)
eb2009asel$v531 <- as.numeric(eb2009asel$v531)
eb2009asel$v531_r[eb2009asel$v531==1] <- 4
eb2009asel$v531_r[eb2009asel$v531==2] <- 3
eb2009asel$v531_r[eb2009asel$v531==3] <- 2
eb2009asel$v531_r[eb2009asel$v531==4] <- 1
table(eb2009asel$v531_r, useNA = "always")
table(eb2009asel$v531, useNA = "always")


table(eb2009asel$v145, useNA = "always")
attributes(eb2009asel$v145) #Environmental protection a personal issue. 
eb2009asel$v145 <- as.numeric(eb2009asel$v145)

table(eb2009asel$v638, useNA = "always") #46 missings on r-l placement. 
eb2009asel$v638 <- as.numeric(eb2009asel$v638)
mean(eb2009asel$v638, na.rm=T)
eb2009asel$v638[is.na(eb2009asel$v638)] <- 4.952906
table(eb2009asel$v642, useNA = "always") #10 missings on eduyrs
eb2009asel$v642 <- as.numeric(eb2009asel$v642)
freq(eb2009asel$v642)
eb2009asel$v642[is.na(eb2009asel$v642)] <- 88
table(eb2009asel$v644, useNA = "always") #no missings gender
table(eb2009asel$v645, useNA = "always") #No missings on age
table(eb2009asel$v650, useNA = "always") #No missings on urbanity

save(eb2009asel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2009asel.Rdata")
```


```{r}
eb2009_2 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2009_2.sav", use.value.labels = T,  to.data.frame = T)

eb2009bsel <- eb2009_2 %>% filter(v6=="The Netherlands") %>%
  select(v1, v8, v385, v364, v363, v374, v392, v393, v394, v395, v396, v397, v398, v399, v387, v388, v389, v390, v391, v439, v440, v441, v442, v445, v279)

attributes(eb2009bsel$v385) #Seriousness climate change
eb2009bsel$v385 <- as.numeric(eb2009bsel$v385)
attributes(eb2009bsel$v364) #Climate change mentioned scores 2. 
attributes(eb2009bsel$v363)
eb2009bsel$gwarming <- NA
eb2009bsel$v363 <- as.numeric(eb2009bsel$v363)
eb2009bsel$gwarming[eb2009bsel$v363==1] <- 1
eb2009bsel$gwarming[eb2009bsel$v363!=1] <- 0
table(eb2009bsel$gwarming, useNA = "always") #Less people (143) mention it at first problem, 343 mention it as first or second problem. 
attributes(eb2009bsel$v392)
eb2009bsel$v392 <- as.numeric(eb2009bsel$v392)
eb2009bsel$v392_r[eb2009bsel$v392==1] <- 4
eb2009bsel$v392_r[eb2009bsel$v392==2] <- 3
eb2009bsel$v392_r[eb2009bsel$v392==3] <- 2
eb2009bsel$v392_r[eb2009bsel$v392==4] <- 1
table(eb2009bsel$v392_r, useNA = "always")
var_label(eb2009bsel$v392_r) <-  "Climate change unstoppable"
table(eb2009bsel$v392, useNA = "always")
eb2009bsel$v396 <- as.numeric(eb2009bsel$v396)
eb2009bsel$v396_r[eb2009bsel$v396==1] <- 4
eb2009bsel$v396_r[eb2009bsel$v396==2] <- 3
eb2009bsel$v396_r[eb2009bsel$v396==3] <- 2
eb2009bsel$v396_r[eb2009bsel$v396==4] <- 1
table(eb2009bsel$v396_r, useNA = "always")
table(eb2009bsel$v396, useNA = "always")
var_label(eb2009bsel$v396_r) <-  "Fighting cc pos impact EU economy"
#397 and 398 also have to be mirrored, but they are split ballot so have to decide what to do with that. 
attributes(eb2009bsel$v399)
eb2009bsel$v399 <- as.numeric(eb2009bsel$v399)
eb2009bsel$v399_r[eb2009bsel$v399==1] <- 4
eb2009bsel$v399_r[eb2009bsel$v399==2] <- 3
eb2009bsel$v399_r[eb2009bsel$v399==3] <- 2
eb2009bsel$v399_r[eb2009bsel$v399==4] <- 1
table(eb2009bsel$v399_r, useNA = "always")
table(eb2009bsel$v399, useNA = "always")
var_label(eb2009bsel$v399_r) <-  "Personally have taken action"

attributes(eb2009bsel$v387) #Nat gov doing enough. Higher score means that they are not doing enough (1 is doing too much)
eb2009bsel$v387 <- as.numeric(eb2009bsel$v387) #SHOULD NOT RECODE IT. DO not use 387_r
attributes(eb2009bsel$v388) #European union doing enough
attributes(eb2009bsel$v389) #Reg/local gov doing enough
attributes(eb2009bsel$v390) #Corporate/industry doing enough
attributes(eb2009bsel$v391) #Citizens doing enough

table(eb2009bsel$v439, useNA = "always") #2 missings.
eb2009bsel$v439 <- as.numeric(eb2009bsel$v439)
freq(eb2009bsel$v439)
eb2009bsel$v439[is.na(eb2009bsel$v439)] <- 88 #Interesting, higher than other samples 
table(eb2009bsel$v440, useNA = "always") #SHOULD NOT USE THIS VAR, is education recoded
table(eb2009bsel$v441, useNA = "always") #Gender no missings
table(eb2009bsel$v442, useNA = "always")  #Age no missings
table(eb2009bsel$v445, useNA = "always") #NO missings
table(eb2009bsel$v279, useNA = "always") #Very poor to very wealthy. 9 missings. 
eb2009bsel$v279 <- as.numeric(eb2009bsel$v279)
mean(eb2009bsel$v279, na.rm = T) 
eb2009bsel$v279[is.na(eb2009bsel$v279)] <- 6.426545

save(eb2009bsel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2009bsel.Rdata")
```


```{r}
#2011 consists of 2 waves as well
eb2011_1 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2011_1.sav", use.value.labels = T,  to.data.frame = T)

eb2011asel <- eb2011_1 %>% filter(v6=="The Netherlands") %>%
  select(v1, v8, v303, v304, v307, v308, v340:v343, v334:v336, v183, v309, v593, v599, v601, v602, v609)

attributes(eb2011asel$v303) #Higher score mostly social and environmental
attributes(eb2011asel$v304) #Influence on life. Recode. 
eb2011asel$v304 <- as.numeric(eb2011asel$v304)
eb2011asel$v304_r[eb2011asel$v304==1] <- 4
eb2011asel$v304_r[eb2011asel$v304==2] <- 3
eb2011asel$v304_r[eb2011asel$v304==3] <- 2
eb2011asel$v304_r[eb2011asel$v304==4] <- 1
table(eb2011asel$v304_r, useNA = "always")
table(eb2011asel$v304, useNA = "always")
var_label(eb2011asel$v304_r) <-  "Environment influence daily life R"

attributes(eb2011asel$v340) #Rightly coded to 343
attributes(eb2011asel$v334)
eb2011asel$v334 <- as.numeric(eb2011asel$v334)
eb2011asel$v334_r[eb2011asel$v334==1] <- 4
eb2011asel$v334_r[eb2011asel$v334==2] <- 3
eb2011asel$v334_r[eb2011asel$v334==3] <- 2
eb2011asel$v334_r[eb2011asel$v334==4] <- 1
table(eb2011asel$v334_r, useNA = "always")
table(eb2011asel$v334, useNA = "always")
var_label(eb2011asel$v334_r) <- "Individual can play role protecting env"
attributes(eb2011asel$v335)
eb2011asel$v335 <- as.numeric(eb2011asel$v335)
eb2011asel$v335_r[eb2011asel$v335==1] <- 4
eb2011asel$v335_r[eb2011asel$v335==2] <- 3
eb2011asel$v335_r[eb2011asel$v335==3] <- 2
eb2011asel$v335_r[eb2011asel$v335==4] <- 1
table(eb2011asel$v335_r, useNA = "always")
table(eb2011asel$v335, useNA = "always")
var_label(eb2011asel$v335_r) <- "Big polluters mainly responsible"

attributes(eb2011asel$v336)
eb2011asel$v336 <- as.numeric(eb2011asel$v336)
eb2011asel$v336_r[eb2011asel$v336==1] <- 4
eb2011asel$v336_r[eb2011asel$v336==2] <- 3
eb2011asel$v336_r[eb2011asel$v336==3] <- 2
eb2011asel$v336_r[eb2011asel$v336==4] <- 1
table(eb2011asel$v336_r, useNA = "always")
table(eb2011asel$v336, useNA = "always")
var_label(eb2011asel$v336_r) <- "Effect on daily life"

attributes(eb2011asel$v183) #Personal importance climate change. 4 cats from very important to not at all important. 
eb2011asel$v183 <- as.numeric(eb2011asel$v183)
eb2011asel$v183_r[eb2011asel$v183==1] <- 4
eb2011asel$v183_r[eb2011asel$v183==2] <- 3
eb2011asel$v183_r[eb2011asel$v183==3] <- 2
eb2011asel$v183_r[eb2011asel$v183==4] <- 1
table(eb2011asel$v183_r, useNA = "always")
table(eb2011asel$v183, useNA = "always")
var_label(eb2011asel$v183_r) <- "Personal importance env protec"


attributes(eb2011asel$v309)
eb2011asel$v309 <- as.numeric(eb2011asel$v309)
eb2011asel$v309_r[eb2011asel$v309==1] <- 4
eb2011asel$v309_r[eb2011asel$v309==2] <- 3
eb2011asel$v309_r[eb2011asel$v309==3] <- 2
eb2011asel$v309_r[eb2011asel$v309==4] <- 1
table(eb2011asel$v309_r, useNA = "always")
table(eb2011asel$v309, useNA = "always")
var_label(eb2011asel$v309_r) <- "Willing purchase env products"

table(eb2011asel$v593, useNA = "always") #57 missings l-r placement. 
eb2011asel$v593 <- as.numeric(eb2011asel$v593)
mean(eb2011asel$v593, na.rm = T)
eb2011asel$v593[is.na(eb2011asel$v593)] <- 5.097236
table(eb2011asel$v599, useNA = "always") #10 missings educyrs
eb2011asel$v599 <- as.numeric(eb2011asel$v599)
mean(eb2011asel$v599, na.rm = T)
eb2011asel$v599[is.na(eb2011asel$v599)] <- 88
table(eb2011asel$v601, useNA = "always") #No missings on gender
table(eb2011asel$v602, useNA = "always") #No missings on age
table(eb2011asel$v609, useNA = "always") #No missings on urbanity

attributes(eb2011asel$v307) #Environmental protection can boost economic growth
eb2011asel$v307 <- as.numeric(eb2011asel$v307)
eb2011asel$v307_r[eb2011asel$v307==1] <- 4
eb2011asel$v307_r[eb2011asel$v307==2] <- 3
eb2011asel$v307_r[eb2011asel$v307==3] <- 2
eb2011asel$v307_r[eb2011asel$v307==4] <- 1
table(eb2011asel$v307_r, useNA = "always")
table(eb2011asel$v307, useNA = "always")
var_label(eb2011asel$v307_r) <- "Env prot can boost economic growth R"

attributes(eb2011asel$v308) #Effective resource use can boost economic growth
eb2011asel$v308 <- as.numeric(eb2011asel$v308)
eb2011asel$v308_r[eb2011asel$v308==1] <- 4
eb2011asel$v308_r[eb2011asel$v308==2] <- 3
eb2011asel$v308_r[eb2011asel$v308==3] <- 2
eb2011asel$v308_r[eb2011asel$v308==4] <- 1
table(eb2011asel$v308_r, useNA = "always")
table(eb2011asel$v308, useNA = "always")
var_label(eb2011asel$v308_r) <- "Eff resource use can boost economic growth"


save(eb2011asel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2011asel.Rdata")

eb2011_2 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2011_2.sav", use.value.labels = T,  to.data.frame = T)

eb2011bsel <- eb2011_2 %>% filter(v6=="The Netherlands") %>% 
  select(v1, v8, v534, v535, v546, v557, v570, v592, v594, v595, v602)

eb2011bsel$v535 <- as.numeric(eb2011bsel$v535)
eb2011bsel$v546 <- as.numeric(eb2011bsel$v546)
attributes(eb2011bsel$v557) #Seriousness climate change problem. Highest score (10) most serious problem. 
attributes(eb2011bsel$v570) 
eb2011bsel$v570 <- as.numeric(eb2011bsel$v570)
eb2011bsel$v570_r[eb2011bsel$v570==1] <- 2
eb2011bsel$v570_r[eb2011bsel$v570==2] <- 1
table(eb2011bsel$v570)
table(eb2011bsel$v570_r)
var_label(eb2011bsel$v570_r) <- "Personally taken action (2 is yes)"
table(eb2011bsel$v592, useNA = "always") #2 missings on education. 
eb2011bsel$v592 <- as.numeric(eb2011bsel$v592)
mean(eb2011bsel$v592, na.rm = T)
eb2011bsel$v592[is.na(eb2011bsel$v592)] <- 88
table(eb2011bsel$v594, useNA = "always") #no missings gender
table(eb2011bsel$v595, useNA = "always") #no missings age
table(eb2011bsel$v602, useNA = "always") #no missing on urbanity

save(eb2011bsel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2011bsel.Rdata")

#2013 
eb2013 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2013.sav", use.value.labels = T,  to.data.frame = T)

eb2013sel <- eb2013 %>% filter(country=="NL - The Netherlands") %>%
  select(studyno1, w1, qa1a, qa5, qa2, qa1b_1, qa1t_1, d10, d8, d11, d25)

attributes(eb2013sel$qa1a) #Climate change as first problem

eb2013sel$cchange <- NA
eb2013sel$qa1a <- as.numeric(eb2013sel$qa1a)
eb2013sel$cchange[eb2013sel$qa1a==1] <- 1
eb2013sel$cchange [eb2013sel$qa1a!=1] <- 0
table(eb2013sel$cchange)

attributes(eb2013sel$qa5) #Personal action taken to fight climate change. 
eb2013sel$qa5 <- as.numeric(eb2013sel$qa5)
eb2013sel$qa5_r[eb2013sel$qa5==1] <- 2
eb2013sel$qa5_r[eb2013sel$qa5==2] <- 1
table(eb2013sel$qa5)
table(eb2013sel$qa5_r)
var_label(eb2013sel$qa5_r) <- "Personally taken action (2 is yes)"

attributes(eb2013sel$qa2) #CC serious problem
eb2013sel$qa2 <- as.numeric(eb2013sel$qa2)
attributes(eb2013sel$qa1b_1) #Mentioned climate change as a serious problem
table(eb2013sel$qa1b_1)
table(eb2013sel$qa1t_1) #Sum 

table(eb2013sel$d10, useNA = "always") #no missings on gender
table(eb2013sel$d8, useNA = "always") #8 missings on educyrs
eb2013sel$d8 <- as.numeric(eb2013sel$d8)
mean(eb2013sel$d8, na.rm=T)
eb2013sel$d8[is.na(eb2013sel$d8)] <- 88
table(eb2013sel$d11, useNA = "always") #No missings on age
table(eb2013sel$d25, useNA = "always") #no missings on urbanity

save(eb2013sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2013sel.Rdata")

eb2014 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2014.sav", use.value.labels = T,  to.data.frame = T)

eb2014sel <- eb2014 %>% filter(country=="NL - The Netherlands") %>%
  select(studyno1, w1,qa9_1, qa9_2, qa7, qa8_1, qa16_1:qa16_6, qa13_1:qa13_3, qa1, qa10, d8, d10, d11, d25)

look_for(eb2014sel, "inc")

attributes(eb2014sel$qa9_1)
eb2014sel$qa9_1 <- as.numeric(eb2014sel$qa9_1)
eb2014sel$qa9_1_r[eb2014sel$qa9_1==1] <- 4
eb2014sel$qa9_1_r[eb2014sel$qa9_1==2] <- 3
eb2014sel$qa9_1_r[eb2014sel$qa9_1==3] <- 2
eb2014sel$qa9_1_r[eb2014sel$qa9_1==4] <- 1
table(eb2014sel$qa9_1_r, useNA = "always")
table(eb2014sel$qa9_1, useNA = "always")
var_label(eb2014sel$qa9_1_r) <- "Env prot can boost economic growth"

attributes(eb2014sel$qa9_2)
eb2014sel$qa9_2 <- as.numeric(eb2014sel$qa9_2)
eb2014sel$qa9_2_r[eb2014sel$qa9_2==1] <- 4
eb2014sel$qa9_2_r[eb2014sel$qa9_2==2] <- 3
eb2014sel$qa9_2_r[eb2014sel$qa9_2==3] <- 2
eb2014sel$qa9_2_r[eb2014sel$qa9_2==4] <- 1
table(eb2014sel$qa9_2_r, useNA = "always")
table(eb2014sel$qa9_2, useNA = "always")
var_label(eb2014sel$qa9_2_r) <- "Eff resource use can boost economic growth"

attributes(eb2014sel$qa7) #Higher score means progress should be based on social and environmental criteria
attributes(eb2014sel$qa8_1)
eb2014sel$qa8_1 <- as.numeric(eb2014sel$qa8_1)
eb2014sel$qa8_1_r[eb2014sel$qa8_1==1] <- 4
eb2014sel$qa8_1_r[eb2014sel$qa8_1==2] <- 3
eb2014sel$qa8_1_r[eb2014sel$qa8_1==3] <- 2
eb2014sel$qa8_1_r[eb2014sel$qa8_1==4] <- 1
table(eb2014sel$qa8_1_r, useNA = "always")
table(eb2014sel$qa8_1, useNA = "always")
var_label(eb2014sel$qa8_1_r) <- "Environment influence on daily life"
attributes(eb2014sel$qa13_1)
eb2014sel$qa13_1 <- as.numeric(eb2014sel$qa13_1)
eb2014sel$qa13_1_r[eb2014sel$qa13_1==1] <- 4
eb2014sel$qa13_1_r[eb2014sel$qa13_1==2] <- 3
eb2014sel$qa13_1_r[eb2014sel$qa13_1==3] <- 2
eb2014sel$qa13_1_r[eb2014sel$qa13_1==4] <- 1
table(eb2014sel$qa13_1_r, useNA = "always")
table(eb2014sel$qa13_1, useNA = "always")
var_label(eb2014sel$qa13_1_r) <- "Individual can play a role"
attributes(eb2014sel$qa13_2)
eb2014sel$qa13_2 <- as.numeric(eb2014sel$qa13_2)
eb2014sel$qa13_2_r[eb2014sel$qa13_2==1] <- 4
eb2014sel$qa13_2_r[eb2014sel$qa13_2==2] <- 3
eb2014sel$qa13_2_r[eb2014sel$qa13_2==3] <- 2
eb2014sel$qa13_2_r[eb2014sel$qa13_2==4] <- 1
table(eb2014sel$qa13_2_r, useNA = "always")
table(eb2014sel$qa13_2, useNA = "always")
var_label(eb2014sel$qa13_2_r) <- "Big polluters mainly responsible"

attributes(eb2014sel$qa13_3)
eb2014sel$qa13_3 <- as.numeric(eb2014sel$qa13_3)
eb2014sel$qa13_3_r[eb2014sel$qa13_3==1] <- 4
eb2014sel$qa13_3_r[eb2014sel$qa13_3==2] <- 3
eb2014sel$qa13_3_r[eb2014sel$qa13_3==3] <- 2
eb2014sel$qa13_3_r[eb2014sel$qa13_3==4] <- 1
table(eb2014sel$qa13_3_r, useNA = "always")
table(eb2014sel$qa13_3, useNA = "always")
var_label(eb2014sel$qa13_3_r) <- "Influences daily quality of life"

attributes(eb2014sel$qa1)
eb2014sel$qa1 <- as.numeric(eb2014sel$qa1)
eb2014sel$qa1_r[eb2014sel$qa1==1] <- 4
eb2014sel$qa1_r[eb2014sel$qa1==2] <- 3
eb2014sel$qa1_r[eb2014sel$qa1==3] <- 2
eb2014sel$qa1_r[eb2014sel$qa1==4] <- 1
table(eb2014sel$qa1_r, useNA = "always")
table(eb2014sel$qa1, useNA = "always")
var_label(eb2014sel$qa1_r) <- "Env protection very important personal"

attributes(eb2014sel$qa10)
eb2014sel$qa10 <- as.numeric(eb2014sel$qa10)
eb2014sel$qa10_r[eb2014sel$qa10==1] <- 4
eb2014sel$qa10_r[eb2014sel$qa10==2] <- 3
eb2014sel$qa10_r[eb2014sel$qa10==3] <- 2
eb2014sel$qa10_r[eb2014sel$qa10==4] <- 1
table(eb2014sel$qa10_r, useNA = "always")
table(eb2014sel$qa10, useNA = "always")
var_label(eb2014sel$qa10_r) <- "Willing to buy env products"

table(eb2014sel$d8, useNA = "always") #1 missing on educ
eb2014sel$d8 <- as.numeric(eb2014sel$d8)
mean(eb2014sel$d8, na.rm=T)
eb2014sel$d8[is.na(eb2014sel$d8)] <- 88 
table(eb2014sel$d10, useNA = "always") #no missings gender
table(eb2014sel$d11, useNA = "always") #no missings on age
table(eb2014sel$d25, useNA = "always") #no missings on urbanity

save(eb2014sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2014sel.Rdata")

#2015
eb2015 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2015.sav", use.value.labels = T,  to.data.frame = T)

eb2015sel <- eb2015 %>% filter(country=="NL - The Netherlands") %>%
  select(studyno1, w1, w3a4a, qa1a, qa1b_1, qa1t_1, qa5, qa2, d8, d10, d11, d25)

attributes(eb2015sel$qa1a)
eb2015sel$cchange <- NA
eb2015sel$qa1a <- as.numeric(eb2015sel$qa1a)
eb2015sel$cchange[eb2015sel$qa1a==1] <- 1
eb2015sel$cchange [eb2015sel$qa1a!=1] <- 0
table(eb2015sel$cchange)

attributes(eb2015sel$qa1t_1) #and this one as well
eb2015sel$qa1t_1 <- as.numeric(eb2015sel$qa1t_1)

attributes(eb2015sel$qa5)
eb2015sel$qa5 <- as.numeric(eb2015sel$qa5)
eb2015sel$qa5_r[eb2015sel$qa5==1] <- 2
eb2015sel$qa5_r[eb2015sel$qa5==2] <- 1
table(eb2015sel$qa5)
table(eb2015sel$qa5_r)
var_label(eb2015sel$qa5_r) <- "Personally taken action (2 is yes)"

attributes(eb2015sel$qa2) #Perception, higher score serious problem

table(eb2015sel$d8, useNA = "always") #5 missings education
eb2015sel$d8 <- as.numeric(eb2015sel$d8)
mean(eb2015sel$d8, na.rm=T)
eb2015sel$d8[is.na(eb2015sel$d8)] <- 88 


table(eb2015sel$d10, useNA = "always") #No missings gender
table(eb2015sel$d11, useNA = "always") #No missings age
table(eb2015sel$d25, useNA = "always") #No missings urbanity

save(eb2015sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2015sel.Rdata")

#2017 consists of 2 waves
eb2017_1 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2017_1.sav", use.value.labels = T,  to.data.frame = T)

eb2017asel <- eb2017_1 %>% filter(country=="NL - The Netherlands") %>%
  select(studyno1, w1, qc1a, qc1b_1, qc1t_1, qc4_1, qc5,qc2, d8, d10, d11, d25)

look_for(eb2017asel, "qc4")
eb2017asel$cchange <- NA
eb2017asel$qc1a <- as.numeric(eb2017asel$qc1a)
eb2017asel$cchange[eb2017asel$qc1a==1] <- 1
eb2017asel$cchange [eb2017asel$qc1a!=1] <- 0
table(eb2017asel$cchange)

attributes(eb2017asel$qc1t_1)
eb2017asel$qc1t_1 <- as.numeric(eb2017asel$qc1t_1) #2 is mentioned
attributes(eb2017asel$qc4_1) #Fighting climate change can boost economic growth

eb2017asel$qc4_1 <- as.numeric(eb2017asel$qc4_1)
eb2017asel$qc4_1_r[eb2017asel$qc4_1==1] <- 4
eb2017asel$qc4_1_r[eb2017asel$qc4_1==2] <- 3
eb2017asel$qc4_1_r[eb2017asel$qc4_1==3] <- 2
eb2017asel$qc4_1_r[eb2017asel$qc4_1==4] <- 1
table(eb2017asel$qc4_1_r, useNA = "always")
table(eb2017asel$qc4_1, useNA = "always")
var_label(eb2017asel$qc4_1_r) <- "Fighting climate change can boost EU economy"

attributes(eb2017asel$qc5)
eb2017asel$qc5 <- as.numeric(eb2017asel$qc5)
eb2017asel$qc5_r[eb2017asel$qc5==1] <- 2
eb2017asel$qc5_r[eb2017asel$qc5==2] <- 1
table(eb2017asel$qc5)
table(eb2017asel$qc5_r)
var_label(eb2017asel$qc5_r) <- "Personally taken action (2 is yes)"

attributes(eb2017asel$qc2)
eb2017asel$qc2 <- as.numeric(eb2017asel$qc2)

table(eb2017asel$d8, useNA = "always") #7 missings on education
eb2017asel$d8 <- as.numeric(eb2017asel$d8)
eb2017asel$d8[is.na(eb2017asel$d8)] <- 88
table(eb2017asel$d10, useNA = "always") #no missings on gender
table(eb2017asel$d11, useNA = "always") #no missings on age
table(eb2017asel$d25, useNA = "always") #no missings on urbanity

save(eb2017asel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2017asel.Rdata")


eb2017_2 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2017_2.sav", use.value.labels = T,  to.data.frame = T)

eb2017bsel <- eb2017_2 %>% filter(country=="NL - The Netherlands") %>%
  select(studyno1, w1, qd7_1:qd7_6, qd5_1:qd5_3, d8, d10, d11, d25)

look_for(eb2017_2, "d25")

attributes(eb2017bsel$qd7_1) #big companies not doing enough. 2 citizens not doing enough, city not doing enough, region not doing enough, nat gov not doing enough, european union not doing enough. The order seems different than other waves so have to check that. 

attributes(eb2017bsel$qd5_1)

eb2017bsel$qd5_1 <- as.numeric(eb2017bsel$qd5_1)
eb2017bsel$qd5_1_r[eb2017bsel$qd5_1==1] <- 4
eb2017bsel$qd5_1_r[eb2017bsel$qd5_1==2] <- 3
eb2017bsel$qd5_1_r[eb2017bsel$qd5_1==3] <- 2
eb2017bsel$qd5_1_r[eb2017bsel$qd5_1==4] <- 1
table(eb2017bsel$qd5_1_r, useNA = "always")
table(eb2017bsel$qd5_1, useNA = "always")
var_label(eb2017bsel$qd5_1_r) <- "Individual can play a role"

eb2017bsel$qd5_2 <- as.numeric(eb2017bsel$qd5_2)
eb2017bsel$qd5_2_r[eb2017bsel$qd5_2==1] <- 4
eb2017bsel$qd5_2_r[eb2017bsel$qd5_2==2] <- 3
eb2017bsel$qd5_2_r[eb2017bsel$qd5_2==3] <- 2
eb2017bsel$qd5_2_r[eb2017bsel$qd5_2==4] <- 1
table(eb2017bsel$qd5_2_r, useNA = "always")
table(eb2017bsel$qd5_2, useNA = "always")
var_label(eb2017bsel$qd5_2_r) <- "Big polluters"

eb2017bsel$qd5_3 <- as.numeric(eb2017bsel$qd5_3)
eb2017bsel$qd5_3_r[eb2017bsel$qd5_3==1] <- 4
eb2017bsel$qd5_3_r[eb2017bsel$qd5_3==2] <- 3
eb2017bsel$qd5_3_r[eb2017bsel$qd5_3==3] <- 2
eb2017bsel$qd5_3_r[eb2017bsel$qd5_3==4] <- 1
table(eb2017bsel$qd5_3_r, useNA = "always")
table(eb2017bsel$qd5_3, useNA = "always")
var_label(eb2017bsel$qd5_3_r) <- "Influences daily life"

table(eb2017bsel$d8, useNA = "always") #8 missings education
eb2017bsel$d8 <- as.numeric(eb2017bsel$d8)
eb2017bsel$d8[is.na(eb2017bsel$d8)] <- 88
table(eb2017bsel$d10, useNA = "always") 
table(eb2017bsel$d11, useNA = "always") 
table(eb2017bsel$d25, useNA = "always") 

save(eb2017bsel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2017bsel.Rdata")

#Lastly, 2021

eb2021 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2021.sav", use.value.labels = T,  to.data.frame = T)

eb2021sel <- eb2021 %>% filter(country=="NL - The Netherlands") %>%
  select(studyno1, w1, qb2, qb1a, qb1b.1, qb1t.1, d8, d10, d11, d25 )

attributes(eb2021sel$qb2) #Serious problem, higher score more of a problem
eb2021sel$qb2 <- as.numeric(eb2021sel$qb2)
attributes(eb2021sel$qb1a) 
eb2021sel$cchange <- NA
eb2021sel$qb1a <- as.numeric(eb2021sel$qb1a)
eb2021sel$cchange[eb2021sel$qb1a==1] <- 1
eb2021sel$cchange [eb2021sel$qb1a!=1] <- 0
table(eb2021sel$cchange, useNA = "always")

attributes(eb2021sel$qb1b.1) 
table(eb2021sel$qb1b.1, useNA = "always") #Still need to read what the differences between these variables are. 
table(eb2021sel$qb1t.1, useNA = "always")
table(eb2021sel$d8, useNA = "always") #No missings on educyrs but 8 people with dk so need to define as missing. 
eb2021sel$d8[eb2021sel$d8=="DK"] <- NA #Check everywhere whether education has outliers
eb2021sel$d8 <- as.numeric(eb2021sel$d8)
eb2021sel$d8[is.na(eb2021sel$d8)] <- 88
describe(eb2021sel$d8)
freq(eb2021sel$d8)
freq(eb2021sel$d11)

hist(eb2021sel$d8)
table(eb2021sel$d10, useNA = "always") #No missings on gender
table(eb2021sel$d11, useNA = "always") #No missings on age
table(eb2021sel$d25, useNA = "always") #No missings on urbanity

save(eb2021sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2021sel.Rdata")
```


```{r}
load("/Users/anuschka/Documents/climatechange/climatechange/eb2017asel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2021sel.Rdata")


#Rename all vars to finally merge into one large dataset
eb2017asel <- eb2017asel %>% dplyr::rename (tarweight=w1, cchange2 = qc1b_1, cchangetot = qc1t_1, ccpercept=qc2, eduyrs = d8, gender = d10, age = d11, urban = d25, prsaction = qc5_r)

eb2017asel <- eb2017asel %>% select (studyno1, tarweight, cchange, cchange2, cchangetot, ccpercept, prsaction, eduyrs, gender, age, urban)

save(eb2017asel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2017asel.Rdata")

eb2021sel <- eb2021sel %>% dplyr::rename(ccpercept = qb2, tarweight = w1, eduyrs = d8, gender = d10, age = d11, urban = d25)

eb2021sel <- eb2021sel %>% dplyr::rename (cchange2 = qb1b.1, cchangetot = qb1t.1)

eb2021sel <- eb2021sel %>% select(studyno1, tarweight, cchange, cchange2, cchangetot, ccpercept, eduyrs, gender, age, urban )

save(eb2021sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2021sel.Rdata")

#2017_2 

load("/Users/anuschka/Documents/climatechange/climatechange/eb2017bsel.Rdata")

eb2017bsel <- eb2017bsel %>% dplyr::rename(tarweight = w1, doprot_comp = qd7_1, doprot_citiz = qd7_2, doprot_city = qd7_3, doprot_region = qd7_4, doprot_natgov = qd7_5, doprot_eu = qd7_6, role_ind = qd5_1_r, bigpol = qd5_2_r, eff_daily = qd5_3_r, eduyrs = d8, gender = d10, age = d11, urban = d25 )

eb2017bsel <- eb2017bsel %>% select(studyno1, tarweight, doprot_comp:doprot_eu, role_ind:eff_daily, eduyrs, gender, age, urban)

save(eb2017bsel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2017bsel.Rdata")

#
load("/Users/anuschka/Documents/climatechange/climatechange/eb2015sel.Rdata")

look_for(eb2015, "climate change")

eb2015sel <- eb2015sel %>% dplyr::rename(tarweight=w1, natweight=w3a4a, cchange2=qa1b_1, cchangetot=qa1t_1, prsaction = qa5_r, ccpercept=qa2, eduyrs = d8, gender = d10, age = d11, urban = d25)

eb2015sel <- eb2015sel %>% select(studyno1, tarweight, natweight, cchange, cchange2, cchangetot, prsaction, ccpercept, eduyrs, gender, age, urban)

save(eb2015sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2015sel.Rdata")
#2014

load("/Users/anuschka/Documents/climatechange/climatechange/eb2014sel.Rdata")
eb2014sel <- eb2014sel %>% dplyr::rename(tarweight=w1, envp_eg = qa9_1_r, effr_eg = qa9_2_r, role_ind=qa13_1_r, big_pol=qa13_2_r, eff_daily=qa13_3_r, env_quallife=qa8_1, doprot_comp=qa16_1, doprot_citiz=qa16_2, doprot_city=qa16_3, doprot_region=qa16_4, doprot_natgov=qa16_5, doprot_eu=qa16_6, pers_imp=qa1_r, buyprod=qa10_r, eduyrs = d8, gender = d10, age = d11, urban = d25)

eb2014sel <- eb2014sel %>% select(studyno1, tarweight, envp_eg, effr_eg, role_ind, big_pol, eff_daily, env_quallife, doprot_comp:doprot_eu, pers_imp, buyprod, eduyrs, gender, age, urban)

save(eb2014sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2014sel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb2013sel.Rdata")
eb2013sel <- eb2013sel %>% dplyr::rename(tarweight=w1, cchange2 = qa1b_1, cchangetot=qa1t_1, prsaction = qa5_r, ccpercept = qa2, eduyrs = d8, gender = d10, age = d11, urban = d25 )

eb2013sel <- eb2013sel %>% dplyr::select(studyno1, tarweight, cchange, cchange2, cchangetot, ccpercept, prsaction, eduyrs, gender, age, urban)

save(eb2013sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2013sel.Rdata")

#2 waves of 2011

load("/Users/anuschka/Documents/climatechange/climatechange/eb2011asel.Rdata")

eb2011asel <- eb2011asel %>% dplyr::rename(studyno1 = v1, tarweight = v8, env_quallife = v304_r, envp_eg = v307_r, effr_eg = v308_r, role_ind = v334_r, big_pol = v335_r, eff_daily = v336_r, pers_imp = v183_r, buyprod = v309_r, lrplace = v593, eduyrs = v599, gender = v601, age=v602, urban=v609 ) 

eb2011asel <- eb2011asel %>% select (studyno1, tarweight, env_quallife, envp_eg, effr_eg, role_ind, big_pol, eff_daily, pers_imp, buyprod, lrplace, eduyrs, gender, age, urban)

save(eb2011asel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2011asel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb2011bsel.Rdata")

eb2011bsel$cchange <- NA
eb2011bsel$v534 <- as.numeric(eb2011bsel$v534)
eb2011bsel$cchange[eb2011bsel$v534==1] <- 1
eb2011bsel$cchange [eb2011bsel$v534!=1] <- 0
table(eb2011bsel$cchange, useNA = "always")

eb2011bsel <- eb2011bsel %>% dplyr::rename (studyno1 = v1, tarweight= v8, cchange2 = v535, cchangetot = v546, ccpercept = v557, prsaction = v570_r, eduyrs = v592, gender = v594, age = v595, urban = v602)

eb2011bsel <- eb2011bsel %>% select (studyno1, tarweight, cchange, cchange2, cchangetot, ccpercept, prsaction, eduyrs, gender, age, urban)

save(eb2011bsel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2011bsel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb2009asel.Rdata")

eb2009asel <- eb2009asel %>% dplyr::rename (studyno1 = v1, tarweight = v8, ccpercept = v522, cc_unstop= v526_r, cc_exag=v527, cc_poseu = v529_r, cc_prsact = v531_r, pers_imp = v145, lrplace = v638, eduyrs= v642, gender = v644, age = v645, urban = v650)

eb2009asel <- eb2009asel %>% select (studyno1, tarweight, ccpercept, cc_unstop, cc_exag, cc_poseu, cc_prsact, pers_imp, lrplace, eduyrs, gender, age, urban)

save(eb2009asel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2009asel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb2009bsel.Rdata")

eb2009bsel <- eb2009bsel %>% dplyr::rename (studyno1 = v1, tarweight = v8, ccpercept = v385, cchange = v364, cc_unstop = v392_r, cc_exag = v393, cc_poseu= v396_r, cc_prsact = v399_r, doprot_natgov = v387, doprot_eu = v388, doprot_region = v389, doprot_comp = v390, doprot_citiz = v391, eduyrs = v439, gender = v441, age = v442, urban = v445)

eb2009bsel <- eb2009bsel %>% select (studyno1, tarweight, ccpercept, cchange, cc_unstop, cc_exag, cc_poseu, cc_prsact, doprot_natgov:doprot_citiz, eduyrs, gender, age, urban)

save(eb2009bsel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2009bsel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb2008sel.Rdata")

table(eb2008sel$v725, useNA = "always")
table(eb2008sel$v705, useNA = "always") #515 missings on perception climate change --> cant include that

eb2008sel <- eb2008sel %>% dplyr::rename(studyno1 = v1, tarweight = v8, cc_unstop = v720_r, cc_exag = v721, cc_poseu = v723_r, cc_prsact = v725_r, lrplace = v761, eduyrs = v765, gender = v767, age = v768, urban = v773)

eb2008sel <- eb2008sel %>% select (studyno1, tarweight, cc_unstop, cc_exag, cc_poseu, cc_prsact, lrplace, eduyrs, gender, age, urban)

save(eb2008sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2008sel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb2007sel.Rdata")

eb2007sel <- eb2007sel %>% dplyr::rename(studyno1 = v1, tarweight = v8, env_vs_ec = v548_r, env_quallife = v544_r, role_ind = v592_r, big_pol = v593_r, eff_daily = v594_r, buyprod = v549_r, pers_imp = v474_r, lrplace = v612, eduyrs = v616, gender = v618, age = v619, urban = v624)

eb2007sel <- eb2007sel %>% select (studyno1, tarweight, env_vs_ec, env_quallife, role_ind, big_pol, eff_daily, buyprod, pers_imp, lrplace, eduyrs, gender, age, urban)

save(eb2007sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2007sel.Rdata")


load("/Users/anuschka/Documents/climatechange/climatechange/eb2004sel.Rdata")

eb2004sel <- eb2004sel %>% dplyr::rename(studyno1 = v1, tarweight = v8, env_quallife = v307_r, lrplace = v579, eduyrs = v583, gender = v585, age = v58, urban = v586)

eb2004sel <- eb2004sel %>% select (studyno1, tarweight, env_quallife, lrplace, eduyrs, gender, age, urban)

save(eb2004sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb2004sel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb1999sel.Rdata") #This wave only has a question Environmental protection policy must also take social and economic effects into account. So won't use this wave. 

load("/Users/anuschka/Documents/climatechange/climatechange/eb1995sel.Rdata")

eb1995sel <- eb1995sel %>% dplyr::rename(studyno1 = v1, tarweight = v8, env_prsimp = problem_r, env_ec_stat = v182, lrplace = v339, educat = v343, gender = v344, age = v345, urban = v354, hh_inc = v355)

eb1995sel <- eb1995sel %>% select(studyno1, tarweight, env_prsimp, env_ec_stat, lrplace, educat, gender, age, urban, hh_inc)

save(eb1995sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb1995sel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb1992sel.Rdata")

look_for(eb1995, "priority")

eb1992sel <- eb1992sel %>% dplyr::rename(studyno1 = v1, tarweight = v8, env_ec_stat = v456, env_prsimp = problem_r, lrplace = v601, eduyrs = v611, gender = v615, age = v616, urban = v645, hh_inc = v649)

eb1992sel <- eb1992sel %>% select (studyno1, tarweight, env_ec_stat, env_prsimp, lrplace, eduyrs, gender, age, urban, hh_inc)

save(eb1992sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb1992sel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb1986sel.Rdata")

eb1986sel <- eb1986sel %>% dplyr::rename(studyno1 = v1, weight = v8, env_ec_stat = v218, env_prsimp = problem_r, lrplace = v270, educat = v284, gender = v290, age = v291, hh_inc = v296, urban = v302 )

eb1986sel <- eb1986sel %>% select(studyno1, weight, env_ec_stat, env_prsimp, lrplace, educat, gender, age, hh_inc, urban)

save(eb1986sel, file="/Users/anuschka/Documents/climatechange/climatechange/eb1986sel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/eb1982sel.Rdata")

table(eb1986sel$env_ec_stat, useNA = "always")
table(eb1982sel$v31, useNA = "always") #The only variable of 1982 (economy vs environment) is not exactly comparable. In later years, there are 3 answer cats while in this wave R could only choose between 2 answer cats. So no 1982.

```

```{r}
#Create one large dataset in smaller steps. 
load("/Users/anuschka/Documents/climatechange/climatechange/eb1986sel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb1992sel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb1995sel.Rdata")

table(eb1986sel$env_ec_stat, useNA = "always") #Not sure if these are totally the same
table(eb1992sel$env_ec_stat, useNA = "always")
table(eb1995sel$env_ec_stat, useNA = "always")

eb1986sel$env_ec_stat <- as.numeric(eb1986sel$env_ec_stat) #1 economy more priority, 2 middle, 3 env priority
eb1992sel$env_ec_stat <- as.numeric(eb1992sel$env_ec_stat)
eb1995sel$env_ec_stat <- as.numeric(eb1995sel$env_ec_stat)

eb1986sel$gender <- as.numeric(eb1986sel$gender)
eb1986sel$gender[eb1986sel$gender== "2"] <- "FEMALE"
eb1986sel$gender[eb1986sel$gender== "1"] <- "MALE"
eb1986sel$gender <- as.factor(eb1986sel$gender)

eb1986sel$surveyyear <- 1986
eb1986sel$n <- 1001 #This if before listwise deletion of missings on the dependent variable
eb1992sel$surveyyear <- 1982
eb1992sel$n <- 1002
eb1995sel$surveyyear <- 1995
eb1995sel$n <- 1008

table(eb1986sel$educat, useNA = "always")
table(eb1995sel$educat, useNA = "always")
table(eb1992sel$eduyrs, useNA = "always")

ebu2000 <- plyr::rbind.fill(eb1986sel, eb1992sel, eb1995sel)

save(ebu2000, file="/Users/anuschka/Documents/climatechange/climatechange/ebu2000.Rdata")

#Now the years under 2010
rm(list = ls())
load("/Users/anuschka/Documents/climatechange/climatechange/eb2004sel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2007sel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2008sel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2009asel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2009bsel.Rdata")


eb2009asel$ccpercept <- as.numeric(eb2009asel$ccpercept)
describe(eb2004sel$eduyrs)
freq(eb2004sel$eduyrs) #62 individuals said they stopped education at 79? Substituted by mean above (where I recoded the variable)
freq(eb2007sel$eduyrs) #Here there are 85 individuals who said they stopped education at 58
freq(eb2008sel$eduyrs) #53 individuals said they stopped school at 59. 
freq(eb2009asel$eduyrs) #Here there are 66 individuals who said they stopped at 61 years. 
freq(eb2009bsel$eduyrs) #Here even 110 individuals who stopped at 61 years. I don't understand what's going on because these are not codes used to express missings. However, I do have to code them as missing. 
#Ok heel dom, met het numeriek maken is dit de cat still studying, maar die heeft R een random nummer gegeven. Weer opnieuw aanpassen dus. 


eb2004sel$surveyyear <- 2004
eb2004sel$n <- 1011
eb2007sel$surveyyear <- 2007
eb2007sel$n <- 1000
eb2008sel$surveyyear <- 2008
eb2008sel$n <- 1041
eb2009asel$surveyyear<- 20091
eb2009asel$n <- 1044
eb2009bsel$surveyyear <- 20092
eb2009bsel$n  <- 996 

eb0010 <- plyr::rbind.fill(eb2004sel, eb2007sel, eb2008sel, eb2009asel, eb2009bsel) #Looks how it should look. 

save(eb0010, file="/Users/anuschka/Documents/climatechange/climatechange/ebu0010.Rdata")

rm(list=ls())

load("/Users/anuschka/Documents/climatechange/climatechange/eb2011asel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2011bsel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2013sel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2014sel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2015sel.Rdata")

#First fix education for these waves as well. DONE

eb2013sel$cchange2 <- as.numeric(eb2013sel$cchange2)
eb2013sel$cchangetot <- as.numeric(eb2013sel$cchange2)
eb2015sel$cchange2 <- as.numeric(eb2015sel$cchange2)
eb2015sel$ccpercept <- as.numeric(eb2015sel$ccpercept)

eb2011asel$surveyyear <- 20111
eb2011asel$n <- 1043
eb2011bsel$surveyyear <- 20112
eb2011bsel$n <- 1001
eb2013sel$surveyyear <- 2013
eb2013sel$n <- 1037
eb2014sel$surveyyear <- 2014
eb2014sel$n <- 1032
eb2015sel$surveyyear <- 2015
eb2015sel$n <- 1008

ebtm15 <- plyr::rbind.fill(eb2011asel, eb2011bsel, eb2013sel, eb2014sel, eb2015sel)

save(ebtm15, file="/Users/anuschka/Documents/climatechange/climatechange/ebutm15.Rdata")

#Now the last waves
load("/Users/anuschka/Documents/climatechange/climatechange/eb2017asel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2017bsel.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb2021sel.Rdata")

eb2017asel$cchange2 <- as.numeric(eb2017asel$cchange2)
eb2021sel$cchange2 <- as.numeric(eb2021sel$cchange2)
eb2021sel$cchangetot <- as.numeric(eb2021sel$cchangetot)

eb2017asel$surveyyear <- 20171
eb2017asel$n <- 1015
eb2017bsel$surveyyear <- 20172 
eb2017bsel$n <- 1013
eb2021sel$surveyyear <- 2021
eb2021sel$n <- 1004

eb17up <- plyr::rbind.fill(eb2017asel, eb2017bsel, eb2021sel)

save(eb17up, file="/Users/anuschka/Documents/climatechange/climatechange/eb17up.Rdata")


load("/Users/anuschka/Documents/climatechange/climatechange/ebu2000.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/ebu0010.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/ebutm15.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/eb17up.Rdata")

ebu2000$gender <- as.numeric(ebu2000$gender)
ebu2000$gender[ebu2000$gender== "1"] <- "Woman"
ebu2000$gender[ebu2000$gender== "2"] <- "Man"
ebu2000$gender <- as.factor(ebu2000$gender)

eb0010$gender <- as.numeric(eb0010$gender)
eb0010$gender[eb0010$gender== "2"] <- "Woman"
eb0010$gender[eb0010$gender== "1"] <- "Man"
eb0010$gender <- as.factor(eb0010$gender)

#female boven
ebtm15$gender <- as.numeric(ebtm15$gender)
ebtm15$gender[ebtm15$gender== "2"] <- "Woman"
ebtm15$gender[ebtm15$gender== "1"] <- "Man"
ebtm15$gender <- as.factor(ebtm15$gender)

eb_tot <- plyr::rbind.fill(ebu2000, eb0010, ebtm15, eb17up)

save(eb_tot, file="/Users/anuschka/Documents/climatechange/climatechange/eb_tot.Rdata")
```

```{r}
#Lr place from 2011 and higher. 
eb2017_1 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2017_1.sav", use.value.labels = T,  to.data.frame = T)

lr2017_1 <- eb2017_1 %>% filter(country=="NL - The Netherlands") %>%
  select(d1)

lr2017_1$surveyyear <- 20171

eb2017_2 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2017_2.sav", use.value.labels = T,  to.data.frame = T)

lr2017_2 <- eb2017_2 %>% filter(country=="NL - The Netherlands") %>%
  select(d1)
lr2017_2$surveyyear <- 20172
look_for(eb2017_2, "placement")

eb2021 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb2021.sav", use.value.labels = T,  to.data.frame = T)

lr2021 <- eb2021 %>% filter(country=="NL - The Netherlands") %>%
  select(d1)

lr2021$surveyyear <- 2021

look_for(eb2021, "placement")

lrplace <- plyr::rbind.fill(lr2017_1, lr2017_2, lr2021)
lrplace <- lrplace %>% dplyr::rename(lrplace = d1)

load("/Users/anuschka/Documents/climatechange/climatechange/eb_tot.Rdata")

##Hier gestrand, geen van de merge opties is degene die ik zoek. 

eb_test <- merge(eb_tot, lrplace_df, by=c("lrplace"), all=F)
eb_test <- dplyr::bind_rows(eb_tot, lrplace_df, by=c("surveyyear", "lrplace"))
eb_test <- dplyr::left_join(eb_tot, lrplace_df)


attributes(lrplace$lrplace) 
attributes(eb_tot$surveyyear)
lrplace$lrplace <- as.numeric(lrplace$lrplace)

lrplace <- apply(lrplace, 2, as.numeric)
eb_tot$surveyyear <- apply(eb_tot$surveyyear)
lrplace_df <- as.data.frame(lrplace)




```

