---
title: "Data preparation Motivaction, LISS and Socon data"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(eval = FALSE)
options(width = 100)
colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 100px;
}
```

In this script, I select, recode and create variables of motivaction data.

```{r}
rm(list = ls())
library(plyr)
library(dplyr)
library(foreign)
library(tidyverse)
library(labelled)
getwd()
```

# Motivaction data {-}
```{r}
#Load in motivaction trend file from local folder
motivaction <- foreign::read.spss("C:/climate_data/motivaction.sav", use.value.labels = T,  to.data.frame = T)

#Both years are in this dataset, so I make sub datasets. I only include group A, as they have filled out the questions that I am interested in. 

table(motivaction$nGroep)

summary(motivaction$nKOP1)

mot2019 <- motivaction %>% filter(nGroep == "Groep A")  %>%
                filter (nKOP1 == "Meting 2019") %>%
            select(nStedelijkheid, nHuishoudsamenstelling, nInkomencat, nGeslacht, xopleidvolt, nOplcatVolt, xlft, iQ20211_8, nQ40, nQ40Extra, iQ41_1:iQ41_5, iQ43, nQ46_1:nQ46_5, iQ50_1, iQ50_2, iQ51_1:iQ51_3, iQ52)

table(mot2019$iQ20211_8, useNA = "always") #only missings so don't include
table(mot2019$nQ40, useNA = "always")
mot2019$cchange_mot <- as.numeric(mot2019$nQ40)
mot2019$cchange_mot
mot2019$cchange_mot <- (as.numeric(mot2019$cchange_mot) - 1)* (6/3) + 1

table(mot2019$iQ41_1, useNA = "always")
mot2019$worried_mot <- as.numeric(mot2019$iQ41_1)
mot2019$worried_mot[mot2019$worried_mot == 6] <- NA

table(mot2019$iQ41_2, useNA = "always")
mot2019$futuregen <- as.numeric(mot2019$iQ41_2)
mot2019$futuregen[mot2019$futuregen == 6] <- NA

table(mot2019$iQ41_3, useNA = "always")
mot2019$nowor <- as.numeric(mot2019$iQ41_3)
mot2019 <- mot2019 %>%
  mutate(across(c(nowor), ~recode(., `1` = 5, `2` = 4, `3` = 3, `4` = 2, `5` = 1)))
table(mot2019$nowor, useNA = "always")
mot2019$nowor[mot2019$nowor == 6] <- NA

#Q41_4 is about Groningen, not really useful
table(mot2019$iQ41_5, useNA = "always")
mot2019$ontime <- as.numeric(mot2019$iQ41_5)
mot2019$ontime[mot2019$ontime == 6] <- NA

table(mot2019$iQ43, useNA = "always")
mot2019$gov <- as.numeric(mot2019$iQ43)
mot2019$gov[mot2019$gov == 6] <- NA



#The following statements are about the responsibility of different groups. There is one answer category that states that the respondent doesn't think measures should be taken. I will code that together with the group "is not responsible" because it both means that you don't think those parties have to act to tackle climate change. 
table(mot2019$nQ46_1, useNA = "always")
mot2019$resp_gov <- as.numeric(mot2019$nQ46_1)
mot2019$resp_gov[mot2019$resp_gov == 5] <- NA
mot2019$resp_gov[mot2019$resp_gov == 4] <- 1
table(mot2019$resp_gov, useNA = "always")
mot2019$resp_gov <- (as.numeric(mot2019$resp_gov) - 1)* (6/3) + 1

table(mot2019$nQ46_2, useNA = "always")
mot2019$resp_comp <- as.numeric(mot2019$nQ46_2)
mot2019$resp_comp[mot2019$resp_comp == 5] <- NA
mot2019$resp_comp[mot2019$resp_comp == 4] <- 1
table(mot2019$resp_comp, useNA = "always")
mot2019$resp_comp <- (as.numeric(mot2019$resp_comp) - 1)* (6/3) + 1

table(mot2019$nQ46_3, useNA = "always")
mot2019$resp_mkb <- as.numeric(mot2019$nQ46_3)
mot2019$resp_mkb[mot2019$resp_mkb == 5] <- NA
mot2019$resp_mkb[mot2019$resp_mkb == 4] <- 1
table(mot2019$resp_mkb, useNA = "always")
mot2019$resp_mkb <- (as.numeric(mot2019$resp_mkb) - 1)* (6/3) + 1

table(mot2019$nQ46_4, useNA = "always")
mot2019$resp_citiz_mot <- as.numeric(mot2019$nQ46_4)
mot2019$resp_citiz_mot[mot2019$resp_citiz_mot == 5] <- NA
mot2019$resp_citiz_mot[mot2019$resp_citiz_mot == 4] <- 1
table(mot2019$resp_citiz_mot, useNA = "always")
mot2019$resp_citiz_mot <- (as.numeric(mot2019$resp_citiz_mot) - 1)* (6/3) + 1

table(mot2019$nQ46_5, useNA = "always")
mot2019$resp_you <- as.numeric(mot2019$nQ46_5)
mot2019$resp_you[mot2019$resp_you == 5] <- NA
mot2019$resp_you[mot2019$resp_you == 4] <- 1
table(mot2019$resp_you, useNA = "always")
mot2019$resp_you <- (as.numeric(mot2019$resp_you) - 1)* (6/3) + 1


table(mot2019$iQ50_1, useNA = "always")
mot2019$pers_resp_mot <- as.numeric(mot2019$iQ50_1)
mot2019$pers_resp_mot[mot2019$pers_resp_mot == 6] <- NA

table(mot2019$iQ50_2, useNA = "always")
mot2019$sust_choice <- as.numeric(mot2019$iQ50_2)
mot2019$sust_choice[mot2019$sust_choice == 6] <- NA

table(mot2019$iQ51_1, useNA = "always")
mot2019$contr <- as.numeric(mot2019$iQ51_1)
mot2019$contr[mot2019$contr == 6] <- NA

table(mot2019$iQ51_2, useNA = "always")
mot2019$energy <- as.numeric(mot2019$iQ51_2)
mot2019$energy[mot2019$energy == 6] <- NA

table(mot2019$iQ51_3, useNA = "always")
mot2019$noidea <- as.numeric(mot2019$iQ51_3)
mot2019$noidea[mot2019$noidea == 6] <- NA

table(mot2019$iQ52, useNA = "always")
mot2019$motiv <- as.numeric(mot2019$iQ52)
mot2019$motiv[mot2019$motiv == 6] <- NA

# Independent variables
# Gender, education, age, urbanity and marital status 
table(mot2019$nGeslacht, useNA = "always")
mot2019$sex <- revalue(mot2019$nGeslacht, c("Man"="1", "Vrouw"="2"))

# 84 have a different marital status than single or living together. I don't want to throw them away, but as they're not living together at least (and have partner influence probably) I will code them in the category of single.
table(mot2019$nHuishoudsamenstelling, useNA = "always")
mot2019$nHuishoudsamenstelling <- as.numeric(mot2019$nHuishoudsamenstelling)
mot2019$marstat[mot2019$nHuishoudsamenstelling ==2 ] <- 1 #Living together
mot2019$marstat[mot2019$nHuishoudsamenstelling != 2] <- 2 #Not living together
mot2019$marstat <- as.factor(mot2019$marstat)
table(mot2019$marstat, useNA = "always")

table(mot2019$xopleidvolt, useNA = "always")
mot2019$educ <- as.numeric(mot2019$xopleidvolt)
table(mot2019$educ, useNA = "always")
mot2019$isced[mot2019$educ == 2 | mot2019$educ == 9] <- 5
mot2019$isced[mot2019$educ == 1] <- 6
mot2019$isced[mot2019$educ == 3 | mot2019$educ == 4] <- 3
mot2019$isced[mot2019$educ == 5 | mot2019$educ == 6] <- 2
mot2019$isced[mot2019$educ == 7] <- 1
mot2019$isced[mot2019$educ == 8] <- 0

mot2019$isced_cat[mot2019$isced <=2] <- "Basic"
mot2019$isced_cat[mot2019$isced == 3 | mot2019$isced == 4] <- "Intermediate"
mot2019$isced_cat[mot2019$isced >=5] <- "Advanced"
mot2019$isced_cat <- factor(mot2019$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(mot2019$isced_cat)

table(mot2019$nStedelijkheid, useNA = "always")
mot2019$urban <- revalue(mot2019$nStedelijkheid, c("Niet stedelijk"= "Low urbanity", "Weinig stedelijk"= "Low urbanity", "Matig stedelijk"="Medium urbanity", "Sterk stedelijk" = "High urbanity", "Zeer sterk stedelijk" = "High urbanity" ))
mot2019$urban  <- factor(mot2019$urban, levels=c("Low urbanity", "Medium urbanity", "High urbanity"), ordered=TRUE)
table(mot2019$urban, useNA = "always") # Urbanity unknown is now a missing

table(mot2019$xlft, useNA = "always") # no missings on age
mot2019$age <- mot2019$xlft

#Let's first save the prepped data. 
save(mot2019, file="./data/all_waves/mot2019.Rdata")


# Now exactly the same for 2021
mot2021 <- motivaction %>% filter(nGroep == "Groep A")  %>%
                filter (nKOP1 == "Meting 2021") %>%
            select(nStedelijkheid, nHuishoudsamenstelling, nInkomencat, nGeslacht, xopleidvolt, nOplcatVolt, xlft, iQ20211_8, nQ40, nQ40Extra, iQ41_1:iQ41_5, iQ43, nQ46_1:nQ46_5, iQ50_1, iQ50_2, iQ51_1:iQ51_3, iQ52)

table(mot2021$iQ20211_8, useNA = "always") #only missings so don't include
table(mot2021$nQ40, useNA = "always")
mot2021$cchange_mot <- as.numeric(mot2021$nQ40)
mot2021$cchange_mot
mot2021$cchange_mot <- (as.numeric(mot2021$cchange_mot) - 1)* (6/3) + 1

table(mot2021$iQ41_1, useNA = "always")
mot2021$worried_mot <- as.numeric(mot2021$iQ41_1)
mot2021$worried_mot[mot2021$worried_mot == 6] <- NA

table(mot2021$iQ41_2, useNA = "always")
mot2021$futuregen <- as.numeric(mot2021$iQ41_2)
mot2021$futuregen[mot2021$futuregen == 6] <- NA

table(mot2021$iQ41_3, useNA = "always")
mot2021$nowor <- as.numeric(mot2021$iQ41_3)
mot2021 <- mot2021 %>%
  mutate(across(c(nowor), ~recode(., `1` = 5, `2` = 4, `3` = 3, `4` = 2, `5` = 1)))
table(mot2021$nowor, useNA = "always")
mot2021$nowor[mot2021$nowor == 6] <- NA

#Q41_4 is about Groningen, not really useful
table(mot2021$iQ41_5, useNA = "always")
mot2021$ontime <- as.numeric(mot2021$iQ41_5)
mot2021$ontime[mot2021$ontime == 6] <- NA

table(mot2021$iQ43, useNA = "always")
mot2021$gov <- as.numeric(mot2021$iQ43)
mot2021$gov[mot2021$gov == 6] <- NA



#The following statements are about the responsibility of different groups. There is one answer category that states that the respondent doesn't think measures should be taken. I will code that together with the group "is not responsible" because it both means that you don't think those parties have to act to tackle climate change. 
table(mot2021$nQ46_1, useNA = "always")
mot2021$resp_gov <- as.numeric(mot2021$nQ46_1)
mot2021$resp_gov[mot2021$resp_gov == 5] <- NA
mot2021$resp_gov[mot2021$resp_gov == 4] <- 1
table(mot2021$resp_gov, useNA = "always")
mot2021$resp_gov <- (as.numeric(mot2021$resp_gov) - 1)* (6/3) + 1

table(mot2021$nQ46_2, useNA = "always")
mot2021$resp_comp <- as.numeric(mot2021$nQ46_2)
mot2021$resp_comp[mot2021$resp_comp == 5] <- NA
mot2021$resp_comp[mot2021$resp_comp == 4] <- 1
table(mot2021$resp_comp, useNA = "always")
mot2021$resp_comp <- (as.numeric(mot2021$resp_comp) - 1)* (6/3) + 1

table(mot2021$nQ46_3, useNA = "always")
mot2021$resp_mkb <- as.numeric(mot2021$nQ46_3)
mot2021$resp_mkb[mot2021$resp_mkb == 5] <- NA
mot2021$resp_mkb[mot2021$resp_mkb == 4] <- 1
table(mot2021$resp_mkb, useNA = "always")
mot2021$resp_mkb <- (as.numeric(mot2021$resp_mkb) - 1)* (6/3) + 1

table(mot2021$nQ46_4, useNA = "always")
mot2021$resp_citiz_mot <- as.numeric(mot2021$nQ46_4)
mot2021$resp_citiz_mot[mot2021$resp_citiz_mot == 5] <- NA
mot2021$resp_citiz_mot[mot2021$resp_citiz_mot == 4] <- 1
table(mot2021$resp_citiz_mot, useNA = "always")
mot2021$resp_citiz_mot <- (as.numeric(mot2021$resp_citiz_mot) - 1)* (6/3) + 1

table(mot2021$nQ46_5, useNA = "always")
mot2021$resp_you <- as.numeric(mot2021$nQ46_5)
mot2021$resp_you[mot2021$resp_you == 5] <- NA
mot2021$resp_you[mot2021$resp_you == 4] <- 1
table(mot2021$resp_you, useNA = "always")
mot2021$resp_you <- (as.numeric(mot2021$resp_you) - 1)* (6/3) + 1


table(mot2021$iQ50_1, useNA = "always")
mot2021$pers_resp_mot <- as.numeric(mot2021$iQ50_1)
mot2021$pers_resp_mot[mot2021$pers_resp_mot == 6] <- NA

table(mot2021$iQ50_2, useNA = "always")
mot2021$sust_choice <- as.numeric(mot2021$iQ50_2)
mot2021$sust_choice[mot2021$sust_choice == 6] <- NA

table(mot2021$iQ51_1, useNA = "always")
mot2021$contr <- as.numeric(mot2021$iQ51_1)
mot2021$contr[mot2021$contr == 6] <- NA

table(mot2021$iQ51_2, useNA = "always")
mot2021$energy <- as.numeric(mot2021$iQ51_2)
mot2021$energy[mot2021$energy == 6] <- NA

table(mot2021$iQ51_3, useNA = "always")
mot2021$noidea <- as.numeric(mot2021$iQ51_3)
mot2021$noidea[mot2021$noidea == 6] <- NA

table(mot2021$iQ52, useNA = "always")
mot2021$motiv <- as.numeric(mot2021$iQ52)
mot2021$motiv[mot2021$motiv == 6] <- NA

# Independent variables
# Gender, education, age, urbanity and marital status 
table(mot2021$nGeslacht, useNA = "always")
mot2021$sex <- revalue(mot2021$nGeslacht, c("Man"="1", "Vrouw"="2"))

# 84 have a different marital status than single or living together. I don't want to throw them away, but as they're not living together at least (and have partner influence probably) I will code them in the category of single.
table(mot2021$nHuishoudsamenstelling, useNA = "always")
mot2021$nHuishoudsamenstelling <- as.numeric(mot2021$nHuishoudsamenstelling)
mot2021$marstat[mot2021$nHuishoudsamenstelling ==2 ] <- 1 #Living together
mot2021$marstat[mot2021$nHuishoudsamenstelling != 2] <- 2 #Not living together
mot2021$marstat <- as.factor(mot2021$marstat)
table(mot2021$marstat, useNA = "always")

table(mot2021$xopleidvolt, useNA = "always")
mot2021$educ <- as.numeric(mot2021$xopleidvolt)
table(mot2021$educ, useNA = "always")
mot2021$isced[mot2021$educ == 2 | mot2021$educ == 9] <- 5
mot2021$isced[mot2021$educ == 1] <- 6
mot2021$isced[mot2021$educ == 3 | mot2021$educ == 4] <- 3
mot2021$isced[mot2021$educ == 5 | mot2021$educ == 6] <- 2
mot2021$isced[mot2021$educ == 7] <- 1
mot2021$isced[mot2021$educ == 8] <- 0

mot2021$isced_cat[mot2021$isced <=2] <- "Basic"
mot2021$isced_cat[mot2021$isced == 3 | mot2021$isced == 4] <- "Intermediate"
mot2021$isced_cat[mot2021$isced >=5] <- "Advanced"
mot2021$isced_cat <- factor(mot2021$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(mot2021$isced_cat)

table(mot2021$nStedelijkheid, useNA = "always")
mot2021$urban <- revalue(mot2021$nStedelijkheid, c("Niet stedelijk"= "Low urbanity", "Weinig stedelijk"= "Low urbanity", "Matig stedelijk"="Medium urbanity", "Sterk stedelijk" = "High urbanity", "Zeer sterk stedelijk" = "High urbanity" ))
mot2021$urban  <- factor(mot2021$urban, levels=c("Low urbanity", "Medium urbanity", "High urbanity"), ordered=TRUE)
table(mot2021$urban, useNA = "always") # Urbanity unknown is now a missing

table(mot2021$xlft, useNA = "always") # no missings on age
mot2021$age <- mot2021$xlft

#Let's first save the prepped data. 
save(mot2021, file="./data/all_waves/mot2021.Rdata")

# Merge the 2 datasets
# This R has some problem with viewing datasets?
# First create the weight variables (done in other script)
utils::View(mot2019) #Like this it works
mot2019$surveyyear <- 2019
mot2021$surveyyear <- 2021

mot2019 <- mot2019 %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, urban, age, cchange_mot, worried_mot, futuregen, nowor, ontime, gov, resp_gov, resp_comp, resp_mkb, resp_citiz_mot, resp_you, pers_resp_mot, sust_choice, contr, energy, noidea, motiv, age_cat, weightvec)

mot2021 <- mot2021 %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, urban, age, cchange_mot, worried_mot, futuregen, nowor, ontime, gov, resp_gov, resp_comp, resp_mkb, resp_citiz_mot, resp_you, pers_resp_mot, sust_choice, contr, energy, noidea, motiv, age_cat, weightvec)

mottotal <- dplyr::bind_rows(mot2019, mot2021)
mottotal$sex <- mottotal$sex - 1

save(mottotal, file="./data/final_data/mottotal.Rdata")

```


# LISS data {-}
```{r}
# The LISS dataset has one question that is asked in 4 waves. The background variables are not part of the dataset, but have to be merged separately. 

#Load both dependent variable and background variables
liss2019 <- foreign::read.spss("C:/climate_data/liss/energy2019.sav", use.value.labels = T,  to.data.frame = T)
liss_bg2019 <- foreign::read.spss("C:/climate_data/liss/background2019.sav", use.value.labels = T,  to.data.frame = T)

# Select the variables that I want
liss2019 <- liss2019 %>% select (su19a304, nomem_encr)
liss_bg2019 <- liss_bg2019 %>% select(nomem_encr, geslacht, leeftijd, woonvorm, burgstat, sted, oplcat)  
  
liss2019 <- merge(liss2019, liss_bg2019, by = "nomem_encr", all = FALSE)

# First check out the dependent variable
table(liss2019$su19a304, useNA = "always") # 178 missings ,ranges from 0 to 10
liss2019$lifestyle <- (as.numeric(liss2019$su19a304) - 1)* (4/10) + 1
table(liss2019$lifestyle, useNA = "always")

# Now the independent variables
# Gender, education, age, urbanity and marital status 
table(liss2019$geslacht, useNA = "always")
liss2019$sex <- revalue(liss2019$geslacht, c("Male"="1", "Female"="2"))

table(liss2019$woonvorm, useNA = "always")
liss2019$woonvorm <- as.numeric(liss2019$woonvorm)
liss2019$marstat[liss2019$woonvorm ==2 | liss2019$woonvorm == 3] <- 1 #Living together
liss2019$marstat[liss2019$woonvorm == 1 | liss2019$woonvorm == 4 | liss2019$woonvorm == 5] <- 2 #Not living together
liss2019$marstat <- as.factor(liss2019$marstat)
table(liss2019$marstat, useNA = "always")

table(liss2019$oplcat, useNA = "always")
liss2019$educ <- as.numeric(liss2019$oplcat)
table(liss2019$educ, useNA = "always")
liss2019$isced[liss2019$educ == 1] <- 1
liss2019$isced[liss2019$educ == 2] <- 2
liss2019$isced[liss2019$educ == 3 | liss2019$educ == 4] <- 3
liss2019$isced[liss2019$educ == 5 | liss2019$educ == 6] <- 5
table(liss2019$isced, useNA = "always")

mean(liss2019$isced, na.rm=T)
liss2019$isced[is.na(liss2019$isced)] <- 3.44

liss2019$isced_cat[liss2019$isced <=2] <- "Basic"
liss2019$isced_cat[liss2019$isced >= 3 & liss2019$isced <= 4] <- "Intermediate"
liss2019$isced_cat[liss2019$isced >=5] <- "Advanced"
liss2019$isced_cat <- factor(liss2019$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(liss2019$isced_cat, useNA = "always") #4 missings 

table(liss2019$sted, useNA = "always")
liss2019$urban <- revalue(liss2019$sted, c("Not urban"= "Low urbanity", "Slightly urban"= "Low urbanity", "Moderately urban"="Medium urbanity", "Very urban" = "High urbanity", "Extremely urban" = "High urbanity" ))
liss2019$urban  <- factor(liss2019$urban, levels=c("Low urbanity", "Medium urbanity", "High urbanity"), ordered=TRUE)
table(liss2019$urban, useNA = "always") # 20 missings

table(liss2019$leeftijd, useNA = "always") # no missings on age
liss2019$age <- liss2019$leeftijd 

# Save dataset 
save(liss2019, file="./data/all_waves/liss2019.Rdata")  

#2020 has 2 waves, one in july and one in october
liss2020a <- foreign::read.spss("C:/climate_data/liss/covid720.sav", use.value.labels = T,  to.data.frame = T)
liss_bg2020a <- foreign::read.spss("C:/climate_data/liss/background720.sav", use.value.labels = T,  to.data.frame = T)

# Select the variables that I want
liss2020a <- liss2020a %>% select (uc20a056, nomem_encr)
liss_bg2020a <- liss_bg2020a %>% select(nomem_encr, geslacht, leeftijd, woonvorm, burgstat, sted, oplcat)  
  
liss2020a <- merge(liss2020a, liss_bg2020a, by = "nomem_encr", all = FALSE)

# First check out the dependent variable
table(liss2020a$uc20a056, useNA = "always") # 91 missings ,ranges from 1 to 10
liss2020a$lifestyle <- (as.numeric(liss2020a$uc20a056) - 1)* (4/9) + 1
table(liss2020a$lifestyle, useNA = "always")

# Now the independent variables
# Gender, education, age, urbanity and marital status 
table(liss2020a$geslacht, useNA = "always")
liss2020a$sex <- revalue(liss2020a$geslacht, c("Male"="1", "Female"="2"))

table(liss2020a$woonvorm, useNA = "always")
liss2020a$woonvorm <- as.numeric(liss2020a$woonvorm)
liss2020a$marstat[liss2020a$woonvorm ==2 | liss2020a$woonvorm == 3] <- 1 #Living together
liss2020a$marstat[liss2020a$woonvorm == 1 | liss2020a$woonvorm == 4 | liss2020a$woonvorm == 5] <- 2 #Not living together
liss2020a$marstat <- as.factor(liss2020a$marstat)
table(liss2020a$marstat, useNA = "always")

table(liss2020a$oplcat, useNA = "always")
liss2020a$educ <- as.numeric(liss2020a$oplcat)
table(liss2020a$educ, useNA = "always")
liss2020a$isced[liss2020a$educ == 1] <- 1
liss2020a$isced[liss2020a$educ == 2] <- 2
liss2020a$isced[liss2020a$educ == 3 | liss2020a$educ == 4] <- 3
liss2020a$isced[liss2020a$educ == 5 | liss2020a$educ == 6] <- 5
table(liss2020a$isced, useNA = "always")

mean(liss2020a$isced, na.rm=T)
liss2020a$isced[is.na(liss2020a$isced)] <- 3.5

liss2020a$isced_cat[liss2020a$isced <=2] <- "Basic"
liss2020a$isced_cat[liss2020a$isced >= 3 & liss2020a$isced <= 4] <- "Intermediate"
liss2020a$isced_cat[liss2020a$isced >=5] <- "Advanced"
liss2020a$isced_cat <- factor(liss2020a$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(liss2020a$isced_cat, useNA = "always")

table(liss2020a$sted, useNA = "always")
liss2020a$urban <- revalue(liss2020a$sted, c("Not urban"= "Low urbanity", "Slightly urban"= "Low urbanity", "Moderately urban"="Medium urbanity", "Very urban" = "High urbanity", "Extremely urban" = "High urbanity" ))
liss2020a$urban  <- factor(liss2020a$urban, levels=c("Low urbanity", "Medium urbanity", "High urbanity"), ordered=TRUE)
table(liss2020a$urban, useNA = "always") # 11 missings

table(liss2020a$leeftijd, useNA = "always") # no missings on age
liss2020a$age <- liss2020a$leeftijd 

# Save dataset 
save(liss2020a, file="./data/all_waves/liss2020a.Rdata")  

# And for the second dataset of 2020
liss2020b <- foreign::read.spss("C:/climate_data/liss/covid1020.sav", use.value.labels = T,  to.data.frame = T)
liss_bg2020b <- foreign::read.spss("C:/climate_data/liss/background1020.sav", use.value.labels = T,  to.data.frame = T)


# Select the variables that I want
liss2020b <- liss2020b %>% select (uc20b056, nomem_encr)
liss_bg2020b <- liss_bg2020b %>% select(nomem_encr, geslacht, leeftijd, woonvorm, burgstat, sted, oplcat)  
  
liss2020b <- merge(liss2020b, liss_bg2020b, by = "nomem_encr", all = FALSE)

# First check out the dependent variable
table(liss2020b$uc20b056, useNA = "always") # 111 missings ,ranges from 1 to 10
liss2020b$lifestyle <- (as.numeric(liss2020b$uc20b056) - 1)* (4/9) + 1
table(liss2020b$lifestyle, useNA = "always")

# Now the independent variables
# Gender, education, age, urbanity and marital status 
table(liss2020b$geslacht, useNA = "always")
liss2020b$sex <- revalue(liss2020b$geslacht, c("Male"="1", "Female"="2"))

table(liss2020b$woonvorm, useNA = "always")
liss2020b$woonvorm <- as.numeric(liss2020b$woonvorm)
liss2020b$marstat[liss2020b$woonvorm ==2 | liss2020b$woonvorm == 3] <- 1 #Living together
liss2020b$marstat[liss2020b$woonvorm == 1 | liss2020b$woonvorm == 4 | liss2020b$woonvorm == 5] <- 2 #Not living together
liss2020b$marstat <- as.factor(liss2020b$marstat)
table(liss2020b$marstat, useNA = "always")

table(liss2020b$oplcat, useNA = "always")
liss2020b$educ <- as.numeric(liss2020b$oplcat)
table(liss2020b$educ, useNA = "always")
liss2020b$isced[liss2020b$educ == 1] <- 1
liss2020b$isced[liss2020b$educ == 2] <- 2
liss2020b$isced[liss2020b$educ == 3 | liss2020b$educ == 4] <- 3
liss2020b$isced[liss2020b$educ == 5 | liss2020b$educ == 6] <- 5
table(liss2020b$isced, useNA = "always")

mean(liss2020b$isced, na.rm=T)
liss2020b$isced[is.na(liss2020b$isced)] <- 3.49

liss2020b$isced_cat[liss2020b$isced <=2] <- "Basic"
liss2020b$isced_cat[liss2020b$isced >= 3 & liss2020b$isced <= 4] <- "Intermediate"
liss2020b$isced_cat[liss2020b$isced >=5] <- "Advanced"
liss2020b$isced_cat <- factor(liss2020b$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(liss2020b$isced_cat, useNA = "always") #4 missings 

table(liss2020b$sted, useNA = "always")
liss2020b$urban <- revalue(liss2020b$sted, c("Not urban"= "Low urbanity", "Slightly urban"= "Low urbanity", "Moderately urban"="Medium urbanity", "Very urban" = "High urbanity", "Extremely urban" = "High urbanity" ))
liss2020b$urban  <- factor(liss2020b$urban, levels=c("Low urbanity", "Medium urbanity", "High urbanity"), ordered=TRUE)
table(liss2020b$urban, useNA = "always") # 9 missings

table(liss2020b$leeftijd, useNA = "always") # no missings on age
liss2020b$age <- liss2020b$leeftijd 

# Save dataset 
save(liss2020b, file="./data/all_waves/liss2020b.Rdata")  

# And the last wave in 2021
liss2021 <- foreign::read.spss("C:/climate_data/liss/covid721.sav", use.value.labels = T,  to.data.frame = T)
liss_bg2021 <- foreign::read.spss("C:/climate_data/liss/background721.sav", use.value.labels = T,  to.data.frame = T)


# Select the variables that I want
liss2021 <- liss2021 %>% select (uc21c056, nomem_encr)
liss_bg2021 <- liss_bg2021 %>% select(nomem_encr, geslacht, leeftijd, woonvorm, burgstat, sted, oplcat)  
  
liss2021 <- merge(liss2021, liss_bg2021, by = "nomem_encr", all = FALSE)

# First check out the dependent variable
table(liss2021$uc21c056, useNA = "always") # 106 missings ,ranges from 1 to 10
liss2021$lifestyle <- (as.numeric(liss2021$uc21c056) - 1)* (4/9) + 1
table(liss2021$lifestyle, useNA = "always")

# Now the independent variables
# Gender, education, age, urbanity and marital status 
table(liss2021$geslacht, useNA = "always")
liss2021$sex <- revalue(liss2021$geslacht, c("Male"="1", "Female"="2"))

table(liss2021$woonvorm, useNA = "always")
liss2021$woonvorm <- as.numeric(liss2021$woonvorm)
liss2021$marstat[liss2021$woonvorm ==2 | liss2021$woonvorm == 3] <- 1 #Living together
liss2021$marstat[liss2021$woonvorm == 1 | liss2021$woonvorm == 4 | liss2021$woonvorm == 5] <- 2 #Not living together
liss2021$marstat <- as.factor(liss2021$marstat)
table(liss2021$marstat, useNA = "always")

table(liss2021$oplcat, useNA = "always")
liss2021$educ <- as.numeric(liss2021$oplcat)
table(liss2021$educ, useNA = "always")
liss2021$isced[liss2021$educ == 1] <- 1
liss2021$isced[liss2021$educ == 2] <- 2
liss2021$isced[liss2021$educ == 3 | liss2021$educ == 4] <- 3
liss2021$isced[liss2021$educ == 5 | liss2021$educ == 6] <- 5
table(liss2021$isced, useNA = "always")

mean(liss2021$isced, na.rm=T)
liss2021$isced[is.na(liss2021$isced)] <- 3.49

liss2021$isced_cat[liss2021$isced <=2] <- "Basic"
liss2021$isced_cat[liss2021$isced >= 3 & liss2021$isced <= 4] <- "Intermediate"
liss2021$isced_cat[liss2021$isced >=5] <- "Advanced"
liss2021$isced_cat <- factor(liss2021$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(liss2021$isced_cat, useNA = "always") #4 missings 

table(liss2021$sted, useNA = "always")
liss2021$urban <- revalue(liss2021$sted, c("Not urban"= "Low urbanity", "Slightly urban"= "Low urbanity", "Moderately urban"="Medium urbanity", "Very urban" = "High urbanity", "Extremely urban" = "High urbanity" ))
liss2021$urban  <- factor(liss2021$urban, levels=c("Low urbanity", "Medium urbanity", "High urbanity"), ordered=TRUE)
table(liss2021$urban, useNA = "always") # 10 missings

table(liss2021$leeftijd, useNA = "always") # no missings on age
liss2021$age <- liss2021$leeftijd 

# Save dataset 
save(liss2021, file="./data/all_waves/liss2021.Rdata")  

# Merge the four datasets, and first creating weights in other script
utils::View(liss2019) 
liss2019$surveyyear <- 2019
liss2020a$surveyyear <- 2020.58
liss2020b$surveyyear <- 2020.83
liss2021$surveyyear <- 2021

liss2019 <- liss2019 %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, age, urban,  lifestyle, age_cat, weightvec)

liss2020a <- liss2020a %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, age, urban, lifestyle, age_cat, weightvec)

liss2020b <- liss2020b %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, age, urban,  lifestyle, age_cat, weightvec)

liss2021 <- liss2021 %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, age, urban,  lifestyle, age_cat, weightvec)

lisstotal <- dplyr::bind_rows(liss2019, liss2020a, liss2020b, liss2021)

lisstotal$sex <- lisstotal$sex - 1

save(lisstotal, file="./data/final_data/lisstotal.Rdata")


```


# SOCON data {-}
```{r}
rm(list=ls())
socon2020 <- foreign::read.spss("C:/climate_data/socon/socon2020.sav", use.value.labels = T,  to.data.frame = T)

utils::View(socon2020)

socon2020 <- socon2020 %>% select(V0013, V0014, V0036, V0037, V0040, V7140)

# First dependent variable
table(socon2020$V7140, useNA = "always") # 113 missings, have to mirror the var
socon2020$fut_gen_socon <- as.numeric(socon2020$V7140)
socon2020 <- socon2020 %>%
  mutate(across(c(fut_gen_socon), ~recode(., `1` = 5, `2` = 4, `3` = 3, `4` = 2, `5` = 1)))
table(socon2020$fut_gen_socon, useNA = "always") 

# Now the independent variable. Urbanity is not asked. 
table(socon2020$V0013, useNA = "always") # 6 missings
socon2020$sex <- revalue(socon2020$V0013, c("male"="1", "female"="2"))

socon2020$age <- 2020 - socon2020$V0014
table(socon2020$age, useNA = "always") #6 missings
mean(socon2020$age, na.rm=T)
socon2020$age[is.na(socon2020$age)] <- 51.52

table(socon2020$V0036, useNA = "always") #72 missings
socon2020$marstat <- as.numeric(socon2020$V0036)
socon2020$marstat <- as.factor(socon2020$marstat)
table(socon2020$marstat, useNA = "always")

table(socon2020$V0040, useNA = "always")
socon2020$educ <- as.numeric(socon2020$V0040)
socon2020$isced[socon2020$educ == 1] <- 0
socon2020$isced[socon2020$educ == 2] <- 1
socon2020$isced[socon2020$educ == 3 | socon2020$educ == 4] <- 2
socon2020$isced[socon2020$educ == 5 | socon2020$educ == 6 | socon2020$educ ==7 | socon2020$educ ==8] <- 3
socon2020$isced[socon2020$educ == 9 | socon2020$educ == 10] <- 5
socon2020$isced[socon2020$educ == 11 | socon2020$educ == 12] <- 6
table(socon2020$isced, useNA = "always") #others now also missing

mean(socon2020$isced, na.rm=T)
socon2020$isced[is.na(socon2020$isced)] <- 3.5567

socon2020$isced_cat[socon2020$isced <=2] <- "Basic"
socon2020$isced_cat[socon2020$isced >= 3 & socon2020$isced <= 4] <- "Intermediate"
socon2020$isced_cat[socon2020$isced >=5] <- "Advanced"
socon2020$isced_cat <- factor(socon2020$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(socon2020$isced_cat, useNA = "always") 


#Save dataset
save(socon2020, file="./data/all_waves/socon2020.Rdata")

# Socon 2021
socon2021 <- foreign::read.spss("C:/climate_data/socon/socon2021.sav", use.value.labels = T,  to.data.frame = T)

table(socon2021$V0014, useNA = "always")

utils::View(socon2021)

socon2021 <- socon2021 %>% select(V0013, V0014, V0036, V0037, V0040, V7140)

# First dependent variable
table(socon2021$V7140, useNA = "always") # 96 missings, have to mirror the var
socon2021$fut_gen_socon <- as.numeric(socon2021$V7140)
socon2021 <- socon2021 %>%
  mutate(across(c(fut_gen_socon), ~recode(., `1` = 5, `2` = 4, `3` = 3, `4` = 2, `5` = 1)))
table(socon2021$fut_gen_socon, useNA = "always") 

# Now the independent variable. Urbanity is not asked. 
table(socon2021$V0013, useNA = "always") # 8 missings
socon2021$sex <- revalue(socon2021$V0013, c("male"="1", "female"="2"))

socon2021$age <- 2021 - socon2021$V0014
table(socon2021$age, useNA = "always") #7 missings
mean(socon2021$age, na.rm=T)
socon2021$age[is.na(socon2021$age)] <- 55.55

table(socon2021$V0036, useNA = "always") #61 missings
socon2021$marstat <- as.numeric(socon2021$V0036)
socon2021$marstat <- as.factor(socon2021$marstat)
table(socon2021$marstat, useNA = "always")

table(socon2021$V0040, useNA = "always")
socon2021$educ <- as.numeric(socon2021$V0040)
socon2021$isced[socon2021$educ == 1] <- 0
socon2021$isced[socon2021$educ == 2] <- 1
socon2021$isced[socon2021$educ == 3 | socon2021$educ == 4] <- 2
socon2021$isced[socon2021$educ == 5 | socon2021$educ == 6 | socon2021$educ ==7 | socon2021$educ ==8] <- 3
socon2021$isced[socon2021$educ == 9 | socon2021$educ == 10] <- 5
socon2021$isced[socon2021$educ == 11 | socon2021$educ == 12] <- 6
table(socon2021$isced, useNA = "always") #others now also missing

mean(socon2021$isced, na.rm=T)
socon2021$isced[is.na(socon2021$isced)] <- 3.6434
socon2021$isced_cat[socon2021$isced <=2] <- "Basic"
socon2021$isced_cat[socon2021$isced >= 3 | socon2021$isced <= 4] <- "Intermediate"
socon2021$isced_cat[socon2021$isced >=5] <- "Advanced"
socon2021$isced_cat <- factor(socon2021$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(socon2021$isced_cat, useNA = "always") 



#Save dataset
save(socon2021, file="./data/all_waves/socon2021.Rdata")

# Socon 2022
socon2022 <- foreign::read.spss("C:/climate_data/socon/socon2022.sav", use.value.labels = T,  to.data.frame = T)

utils::View(socon2022)

socon2022 <- socon2022 %>% select(V0013, V0014, V0036, V0037, V0040, V7140)

# First dependent variable
table(socon2022$V7140, useNA = "always") # 151 missings, have to mirror the var
socon2022$fut_gen_socon <- as.numeric(socon2022$V7140)
socon2022 <- socon2022 %>%
  mutate(across(c(fut_gen_socon), ~recode(., `1` = 5, `2` = 4, `3` = 3, `4` = 2, `5` = 1)))
table(socon2022$fut_gen_socon, useNA = "always") 

# Now the independent variable. Urbanity is not asked. 
table(socon2022$V0013, useNA = "always") # 3 missings, 6 other (also NA)
socon2022$sex <- revalue(socon2022$V0013, c("male"="1", "female"="2", "other" = NA))
table(socon2022$sex, useNA = "always")

socon2022$age <- 2022 - socon2022$V0014
table(socon2022$age, useNA = "always") #1 missing
mean(socon2022$age, na.rm=T)
socon2022$age[is.na(socon2022$age)] <- 51.17

table(socon2022$V0036, useNA = "always") #102 missings
socon2022$marstat <- as.numeric(socon2022$V0036)
socon2022$marstat <- as.factor(socon2022$marstat)
table(socon2022$marstat, useNA = "always")

table(socon2022$V0040, useNA = "always")
socon2022$educ <- as.numeric(socon2022$V0040)
socon2022$isced[socon2022$educ == 1] <- 0
socon2022$isced[socon2022$educ == 2] <- 1
socon2022$isced[socon2022$educ == 3 | socon2022$educ == 4] <- 2
socon2022$isced[socon2022$educ == 5 | socon2022$educ == 6 | socon2022$educ ==7 | socon2022$educ ==8] <- 3
socon2022$isced[socon2022$educ == 9 | socon2022$educ == 10] <- 5
socon2022$isced[socon2022$educ == 11 | socon2022$educ == 12] <- 6
table(socon2022$isced, useNA = "always") #others now also missing

mean(socon2022$isced, na.rm=T)
socon2022$isced[is.na(socon2022$isced)] <- 3.5922
socon2022$isced_cat[socon2022$isced <=2] <- "Basic"
socon2022$isced_cat[socon2022$isced >= 3 & socon2022$isced <= 4] <- "Intermediate"
socon2022$isced_cat[socon2022$isced >=5] <- "Advanced"
socon2022$isced_cat <- factor(socon2022$isced_cat, levels=c("Basic", "Intermediate", "Advanced"), ordered=TRUE)
table(socon2022$isced_cat, useNA = "always") 

#Save dataset
save(socon2022, file="./data/all_waves/socon2022.Rdata")

# Merge the datasets
utils::View(socon2020) #Like this it works
load("./data/all_waves/socon2020.Rdata")
socon2020$surveyyear <- 2020
socon2021$surveyyear <- 2021
socon2022$surveyyear <- 2022

socon2020 <- socon2020 %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, age,  fut_gen_socon, age_cat, weightvec)

socon2021 <- socon2021 %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, age,  fut_gen_socon, age_cat, weightvec)

socon2022 <- socon2022 %>% select(surveyyear, sex, marstat, educ, isced, isced_cat, age,  fut_gen_socon, age_cat, weightvec)

#Fix the anesrake issue with age in 2021
socon2021$age_cat[socon2021$age >=15 & socon2021$age <= 30] <- 1
socon2021$age_cat[socon2021$age >=31 & socon2021$age <= 45] <- 2
socon2021$age_cat[socon2021$age >=46 & socon2021$age <= 60] <- 3
socon2021$age_cat[socon2021$age >=61] <- 4

socontotal <- dplyr::bind_rows(socon2020, socon2021, socon2022)
socontotal$sex <- socontotal$sex - 1

save(socontotal, file="./data/final_data/socontotal.Rdata")
```

