---
title: "Meta-regression weighted gamlss models"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE}
#knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(number_sections = FALSE)
options(width = 100)
colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 100px;
}
```

In this script, I perform meta-analyses for the models and test the hypotheses. With the surveyyear instead of time. 

```{r, results = 'hide', warning=FALSE, message=FALSE}
rm(list=ls())
library(meta)
library(metafor)
library(dplyr)
library(kableExtra)
library(fastDummies)
library(modelsummary)
library(broom.mixed)
library(ggplot2)

set.seed(1)

```

## Forest plots {-}

```{r, results='hide', warning=FALSE}
# With the final data
load("./data/meta_analysis/total_reg_results_gam_w_srvy.RData")

# Delete outlier
total_reg_results <- subset(total_reg_results, subset = dep_var != "cc_unstop")
```


```{r, results='hide', warning=FALSE}
# Step 1. Estimate the empty model without moderators to make the forest plots. 

# Delete outlier
#total_reg_results <- subset(total_reg_results, subset = dep_var != "cc_unstop")
model_step_1_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              method = "ML",
              test = "knha")

model_step_1_att
```

```{r}
# Make a forest plot of the above model (time-only)
forest_plot_mean <- total_reg_results %>%
  select(dep_var, dep_var_name, colour, mu_time, mu_time_sd, ambiguous, attitude_cat)

forest_plot_mean$num <- runif(70, 1, 80)
forest_plot_mean$ci_upper <- forest_plot_mean$mu_time + (1.96*forest_plot_mean$mu_time_sd)
forest_plot_mean$ci_lower <- forest_plot_mean$mu_time - (1.96*forest_plot_mean$mu_time_sd)

pooled_df <- data.frame(matrix(ncol = 7, nrow = 1))
colnames(pooled_df) <- c("dep_var_name", "mu_time", "ci_upper", "ci_lower", "attitude_cat", "ambiguous", "num")
pooled_df$dep_var_name <- "Pooled effect"
pooled_df$mu_time <- 0.0265
pooled_df$ci_upper <- model_step_1_att$ci.ub
pooled_df$ci_lower <- model_step_1_att$ci.lb
pooled_df$attitude_cat <- "None"
pooled_df$ambiguous <- "No"
pooled_df$num <- 1


library(plyr)
forest_plot_mean <- rbind.fill(forest_plot_mean, pooled_df)

# Use a palette of colours suitable for colourblind people
cbPalette <- c( "#E69F00", "#56B4E9", "#009E73","#999999", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# An ordered plot based on effect size, but with the pooled effect at the bottom
forest_plot_mean$pooled[forest_plot_mean$num ==1] <- "Yes"
forest_plot_mean$pooled[is.na(forest_plot_mean$pooled)] <- "No"
forest_plot_mean$order_var <- ifelse(forest_plot_mean$pooled == "Yes", Inf, forest_plot_mean$mu_time)

plot2 <- ggplot(data=forest_plot_mean, aes(x=reorder(dep_var_name, -order_var), y=mu_time, ymin=ci_lower, ymax=ci_upper)) +
         geom_pointrange(aes(color = attitude_cat )) + 
        geom_point(aes(shape = ambiguous)) +
        geom_hline(yintercept=0, lty=2) +  # add a dotted line at x=1 after flip
        coord_flip() +  # flip coordinates (puts labels on y axis)
        xlab("Climate change attitude") + ylab("Observed outcome (95% CI)") +
        theme_classic() +
  scale_colour_manual(values=cbPalette,
                      name  ="Attitude Category",
                            breaks=c("behavioral", "affective", "cognitive"),
                            labels=c("Behavioral", "Affective", "Cognitive")) + 
  scale_shape_manual(values=c(0, 13),
                     name  ="Ambiguous Item",
                           breaks=c("No", "Yes"),
                           labels=c("No", "Yes")) + 
  theme(text=element_text(size=8,  family="serif")) 
print(plot2)
#ggsave("fp_ordered.png", width = 7, height = 5, path = "./output/forest_plot_mean_ordered_surveyyear.png")
```


```{r, warning=FALSE}
# Repeat step 1, but then for the polarization (variance)
model_step_1_var <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              method = "ML",
              test = "knha")

model_step_1_var
```

```{r}
set.seed(1)
forest_plot_pol<- total_reg_results %>%
  select(dep_var, dep_var_name, colour, sig_time, sig_time_sd, ambiguous, attitude_cat)

forest_plot_pol$num <- runif(70, 1, 80)
forest_plot_pol$ci_upper <- forest_plot_pol$sig_time + (1.96*forest_plot_pol$sig_time_sd)
forest_plot_pol$ci_lower <- forest_plot_pol$sig_time - (1.96*forest_plot_pol$sig_time_sd)

# Add the pooled effect 
pooled_pol_df <- data.frame(matrix(ncol = 7, nrow = 1))
colnames(pooled_pol_df) <- c("dep_var_name", "sig_time", "ci_upper", "ci_lower", "attitude_cat", "ambiguous", "num")
pooled_pol_df$dep_var_name <- "Pooled effect"
pooled_pol_df$sig_time <- -0.0075
pooled_pol_df$ci_upper <- model_step_1_var$ci.ub
pooled_pol_df$ci_lower <- model_step_1_var$ci.lb
pooled_pol_df$attitude_cat <- "None"
pooled_pol_df$ambiguous <- "No"
pooled_pol_df$num <- 1

forest_plot_pol <- rbind.fill(forest_plot_pol, pooled_pol_df)

# An ordered plot based on effect size, but with the pooled effect at the bottom
forest_plot_pol$pooled[forest_plot_pol$num ==1] <- "Yes"
forest_plot_pol$pooled[is.na(forest_plot_pol$pooled)] <- "No"
forest_plot_pol$order_var <- ifelse(forest_plot_pol$pooled == "Yes", Inf, forest_plot_pol$sig_time)

fp_pol2 <- ggplot(data=forest_plot_pol, aes(x=reorder(dep_var_name, -order_var), y=sig_time, ymin=ci_lower, ymax=ci_upper)) +
         geom_pointrange(aes(color = attitude_cat )) + 
        geom_point(aes(shape = ambiguous)) +
        geom_hline(yintercept=0, lty=2) +  # add a dotted line at x=1 after flip
        coord_flip() +  # flip coordinates (puts labels on y axis)
        xlab("Climate change attitude") + ylab("Observed outcome (95% CI)") +
        theme_classic() +
  scale_colour_manual(values=cbPalette,
                      name  ="Attitude Category",
                            breaks=c("behavioral", "affective", "cognitive"),
                            labels=c("Behavioral", "Affective", "Cognitive")) + 
  scale_shape_manual(values=c(0, 13),
                     name  ="Ambiguous Item",
                           breaks=c("No", "Yes"),
                           labels=c("No", "Yes")) + 
  theme(text=element_text(size=8,  family="serif")) + 
  ylim(-0.5, 0.5) 

print(fp_pol2)

#ggsave("fp_pol_ordered.png", width = 7, height = 5, path = "./output/forest_plot_ordered_surveyyear.png")
```

## Step 2 until 4 meta-regression {-}

```{r, warning=FALSE}
# Check funnel plot asymmetry
funnel(model_step_1_att, col = "steelblue", main = "Funnel Plot")
funnel(model_step_1_var, col = "steelblue", main = "Funnel Plot")

beggs_asymm_mu <- cor.test(rank(total_reg_results$mu_time), total_reg_results$mu_time_sd, method = "kendall") # sig
beggs_assym_sigma <- cor.test(rank(total_reg_results$sig_time), total_reg_results$sig_time_sd, method = "kendall") # not sig

egger_mu <- regtest(total_reg_results$mu_time, total_reg_results$mu_time_sd) # not sig
egger_sig <- regtest(total_reg_results$sig_time, total_reg_results$sig_time_sd) # not sig

duval_tweedie_mu <- trimfill(total_reg_results$mu_time, total_reg_results$mu_time_sd) # insig
duval_tweedie_sig <- trimfill(total_reg_results$sig_time, total_reg_results$sig_time_sd) # insig
```

```{r, results='hide', warning=FALSE}
#Step 2. Empty model with meta-level indicators, first only with mean year. 
# First I have to give mean_year a meaning
table(total_reg_results$mean_year)
total_reg_results$mean_year_centered <- total_reg_results$mean_year - mean(total_reg_results$mean_year)

#From the plot we saw that behavioral shows something else than the other 2, so set that as the reference category.
table(total_reg_results$attitude_cat)
total_reg_results$attitude_cat <- factor(total_reg_results$attitude_cat)
total_reg_results$attitude_cat <- relevel(total_reg_results$attitude_cat, ref = "behavioral") # Other ref cats also insig for mean, for variance beh as ref cat sig
 
model_step_2_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat,
              method = "ML",
              test = "knha")

summary(model_step_2_att)

# Save dataset with new variables
#save(total_reg_results, file= "./data/meta_analysis/total_reg_results_gam_w_new.RData" )
```


```{r, results='hide', warning=FALSE}
# Step 2 variance
#Step 2. Empty model with meta-level indicators
model_step_2_var <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~ attitude_cat, # behavioral as ref cat, sig
              method = "ML",
              test = "knha")

model_step_2_var
```

```{r, results='hide', warning=FALSE}
# Step 3. Model with 2 meta-level vars variables
model_step_3_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat + mean_year_centered,
              method = "ML",
              test = "knha")

model_step_3_att

model_step_3_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~  first_year + mean_year_centered,
              method = "ML",
              test = "knha")

model_step_3_att

vif(model_step_3_att)
# Step 4. Model with all metalevel variables
# First check the correlation between the numeric vars
total_reg_results[,c("pec_miss", "or_scale", "national", "mean_year_centered")] %>% cor() # low correlations

total_reg_results$data <- factor(total_reg_results$data)
total_reg_results$data <- relevel(total_reg_results$data, ref = "EB")

total_reg_results$random_cat <- 
  sample(c('A', 'B', "C", "D", "E", "F", "G", "H"), 70, replace=TRUE)
total_reg_results$random_cat <- as.factor(total_reg_results$random_cat)

model_step_4_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat + mean_year_centered + ambiguous + national + or_scale + pec_miss + data + nr_waves,
              method = "ML",
              test = "knha")

model_step_4_att
```

```{r, results='hide', warning=FALSE}
# Step 3. Variance
model_step_3_var <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~  attitude_cat + mean_year_centered,
              method = "ML",
              test = "knha")

model_step_3_var

# Step 4. Variance
model_step_4_var <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~  attitude_cat +  mean_year_centered + ambiguous + national + or_scale + pec_miss + data + nr_waves,
              method = "ML",
              test = "knha")

model_step_4_var
```

## Put the results in kable table {-}

```{r}
models <- list("M1" = model_step_1_att, "M2" = model_step_2_att, "M3" = model_step_3_att, "M4" = model_step_4_att, "M1" =  model_step_1_var, "M2"= model_step_2_var, "M3"=  model_step_3_var, "M4" = model_step_4_var)

modelsummary(models, output = "kableExtra", statistic = 'std.error', stars = TRUE, shape = term ~ model + statistic, title = "
Table 3. Meta-regression on climate change attitudes and polarization.", fmt = fmt_statistic(estimate = 3, std.error =3), coef_rename = c("overall" ="Intercept", 
           "intercept" = "Intercept", 
           "attitude_cataffective" = "Affective attitude (ref = beh)",
           "attitude_catcognitive" = "Cognitive attitude", 
           "mean_year_centered" =	"Mean year centered", 
           "ambiguousYes" = "Ambiguous (ref = no)",
           "national" = "National (ref = no)", 
           "or_scale" = "Original scale", 
            "pec_miss" = "Perc. missings", 
           "dataESS"= "ESS (ref = EB)", 
           "dataEVS"= "EVS", 
           "dataISSP" = "ISSP", 
           "dataLISS"= "LISS", 
           "dataMOT" = "MOT", 
           "nr_waves" = "Nr. of waves"), gof_map = NA) %>%
  kable_classic_2(html_font = "Times", fixed_thead = T, full_width = F) %>%
   add_header_above(c(" " = 1, "Mu" = 8, "Sigma" = 8))%>%
    save_kable("./output/meta_regression_table_NEW_FEB24.html")
```


## Fixed effects {-}
```{r}
# Mean attitudes
# Step 1
model_step_1_att_f <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              method = "FE",
              test = "z")

model_step_1_att_f

model_step_2_att_f <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat,
              method = "FE",
              test = "z")

summary(model_step_2_att_f)

model_step_3_att_f <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat + mean_year_centered,
              method = "FE",
              test = "z")

model_step_3_att_f

model_step_4_att_f <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat + mean_year_centered + ambiguous + national + or_scale + pec_miss + data + nr_waves,
              method = "FE",
              test = "z")

model_step_4_att_f
```

```{r}
# Fixed effects variance
model_step_1_var_f <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              method = "FE",
              test = "z")

model_step_1_var_f

model_step_2_var_f <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~ attitude_cat, # beh as ref cat, sig
              method = "FE",
              test = "z")

model_step_2_var_f

model_step_3_var_f <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~  attitude_cat + mean_year_centered,
              method = "FE",
              test = "z")

model_step_3_var_f

# Step 4. Variance
model_step_4_var_f <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~  attitude_cat +  mean_year_centered + ambiguous + national + or_scale + pec_miss + data + nr_waves,
              method = "FE",
              test = "z")

model_step_4_var_f
```


```{r}
# Also put the fixed effects in a table
modelsf <- list("M1" = model_step_1_att_f, "M2" = model_step_2_att_f, "M3" = model_step_3_att_f, "M4" = model_step_4_att_f, "M1" =  model_step_1_var_f, "M2"= model_step_2_var_f, "M3"=  model_step_3_var_f, "M4" = model_step_4_var_f)

modelsummary(modelsf, output = "kableExtra", statistic = 'std.error', stars = TRUE, shape = term ~ model + statistic, title = "
Appendix X. Fixed effect meta-regression on climate change attitudes and polarization.", fmt = fmt_statistic(estimate = 3, std.error =3), coef_rename = c("overall" ="Intercept", 
           "intercept" = "Intercept", 
           "attitude_cataffective" = "Affective attitude (ref = beh)",
           "attitude_catcognitive" = "Cognitive attitude", 
           "mean_year_centered" =	"Mean year centered", 
           "ambiguousYes" = "Ambiguous (ref = no)",
           "national" = "National (ref = no)", 
           "or_scale" = "Original scale", 
            "pec_miss" = "Perc. missings", 
           "dataESS"= "ESS (ref = EB)", 
           "dataEVS"= "EVS", 
           "dataISSP" = "ISSP", 
           "dataLISS"= "LISS", 
           "dataMOT" = "MOT", 
           "nr_waves" = "Nr. of waves"), gof_map = NA) %>%
  kable_classic_2(html_font = "Times", fixed_thead = T, full_width = F) %>%
   add_header_above(c(" " = 1, "Mu" = 8, "Sigma" = 8))%>%
    save_kable("./output/appendix/fixed_meta_regression_table.html")
```

## Repeat main analyses without ambiguous variables and make table {-}

```{r}
# Check leaving out the ambiguous variables
ex_amb_df <- subset(total_reg_results, subset = ambiguous == "No")

model_step_1_att_amb <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = ex_amb_df,
              method = "ML",
              test = "knha")

model_step_1_att_amb

model_step_2_att_amb <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = ex_amb_df,
              mods = ~ attitude_cat,
              method = "ML",
              test = "knha")

model_step_2_att_amb

model_step_3_att_amb <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = ex_amb_df,
              mods = ~ attitude_cat + mean_year_centered,
              method = "ML",
              test = "knha")

model_step_3_att_amb


model_step_4_att_amb <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = ex_amb_df,
              mods = ~ attitude_cat + mean_year_centered +  national + or_scale + pec_miss + data + nr_waves,
              method = "ML",
              test = "knha")

model_step_4_att_amb

# Variance
model_step_1_var_amb <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = ex_amb_df,
              method = "ML",
              test = "knha")

model_step_1_var_amb

model_step_2_var_amb <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = ex_amb_df,
              mods = ~ attitude_cat, 
              method = "ML",
              test = "knha")

model_step_2_var_amb

model_step_3_var_amb <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = ex_amb_df,
              mods = ~  attitude_cat + mean_year_centered,
              method = "ML",
              test = "knha")

model_step_3_var_amb

model_step_4_var_amb <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = ex_amb_df,
              mods = ~  attitude_cat +  mean_year_centered + national + or_scale + pec_miss + data + nr_waves,
              method = "ML",
              test = "knha")

model_step_4_var_amb


# Still need to adjust, the fit statitics are not complete
models <- list("M1" = model_step_1_att_amb, "M2" = model_step_2_att_amb, "M3" = model_step_3_att_amb, "M4" = model_step_4_att_amb, "M1" =  model_step_1_var_amb, "M2"= model_step_2_var_amb, "M3"=  model_step_3_var_amb, "M4" = model_step_4_var_amb)


modelsummary(models, output = "kableExtra", statistic = 'std.error', stars = TRUE, shape = term ~ model + statistic, title = "Appendix X. Meta-regression excluding ambiguous variables.", fmt = fmt_statistic(estimate = 3, std.error =3), coef_rename = c("overall" ="Intercept", 
           "intercept" = "Intercept", 
           "attitude_cataffective" = "Affective attitude (ref = beh)",
           "attitude_catcognitive" = "Cognitive attitude", 
           "mean_year_centered" =	"Mean year centered", 
           "national" = "National (ref = no)", 
           "or_scale" = "Original scale", 
            "pec_miss" = "Perc. missings", 
           "dataESS"= "ESS (ref = EB)", 
           "dataEVS"= "EVS", 
           "dataISSP" = "ISSP", 
           "dataLISS"= "LISS", 
           "dataMOT" = "MOT", 
           "nr_waves" = "Nr. of waves"), gof_map = NA) %>%
  kable_classic_2(html_font = "Times", fixed_thead = T, full_width = F) %>%
   add_header_above(c(" " = 1, "Mu" = 8, "Sigma" = 8))%>%
    save_kable("./output/appendix/meta_regression_table_excluding_ambiguous.html")
```


## Repeat main analyses without outlier and make table {-}

```{r}
# Load the data
load("./data/meta_analysis/total_reg_results_gam_w_new.RData")

# Run the first model and check for outliers
model_step_1_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              method = "ML",
              test = "knha")

model_step_1_att

inf <- influence(model_step_1_att) # There is one outlier

# Delete outlier
total_reg_results <- subset(total_reg_results, subset = dep_var != "cc_unstop")

# Run the same analyses
model_step_1_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              method = "ML",
              test = "knha")

model_step_1_att

model_step_1_var <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              method = "ML",
              test = "knha")

model_step_1_var

model_step_2_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat,
              method = "ML",
              test = "knha")

summary(model_step_2_att)

model_step_2_var <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~ attitude_cat, # cogn as ref cat, sig
              method = "ML",
              test = "knha")

model_step_2_var

model_step_3_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat + mean_year_centered,
              method = "ML",
              test = "knha")

model_step_3_att

model_step_4_att <- rma(yi = mu_time,
              sei = mu_time_sd,
              data = total_reg_results,
              mods = ~ attitude_cat + mean_year_centered + ambiguous + national + or_scale + pec_miss + data + nr_waves,
              method = "ML",
              test = "knha")

model_step_4_att

model_step_3_var <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~  attitude_cat + mean_year_centered,
              method = "ML",
              test = "knha")

model_step_3_var

model_step_4_var <- rma(yi = sig_time_std,
              sei = sig_time_sd_std,
              data = total_reg_results,
              mods = ~  attitude_cat +  mean_year_centered + ambiguous + national + or_scale + pec_miss + data + nr_waves,
              method = "ML",
              test = "knha")

model_step_4_var

# Put them in a table
models <- list("M1" = model_step_1_att, "M2" = model_step_2_att, "M3" = model_step_3_att, "M4" = model_step_4_att, "M1" =  model_step_1_var, "M2"= model_step_2_var, "M3"=  model_step_3_var, "M4" = model_step_4_var)
    

models <- list("M1" = model_step_1_att, "M2" = model_step_2_att, "M3" = model_step_3_att, "M4" = model_step_4_att, "M1" =  model_step_1_var, "M2"= model_step_2_var, "M3"=  model_step_3_var, "M4" = model_step_4_var)

modelsummary(models, output = "kableExtra", statistic = 'std.error', stars = TRUE, shape = term ~ model + statistic, title = "
Appendix X. Meta-regression on climate change attitudes and polarization including outlier.", fmt = fmt_statistic(estimate = 3, std.error =3), coef_rename = c("overall" ="Intercept", 
           "intercept" = "Intercept", 
           "attitude_cataffective" = "Affective attitude (ref = beh)",
           "attitude_catcognitive" = "Cognitive attitude", 
           "mean_year_centered" =	"Mean year centered", 
           "ambiguousYes" = "Ambiguous (ref = no)",
           "national" = "National (ref = no)", 
           "or_scale" = "Original scale", 
            "pec_miss" = "Perc. missings", 
           "dataESS"= "ESS (ref = EB)", 
           "dataEVS"= "EVS", 
           "dataISSP" = "ISSP", 
           "dataLISS"= "LISS", 
           "dataMOT" = "MOT", 
           "nr_waves" = "Nr. of waves"), gof_map = NA) %>%
  kable_classic_2(html_font = "Times", fixed_thead = T, full_width = F) %>%
   add_header_above(c(" " = 1, "Mu" = 8, "Sigma" = 8))%>%
    save_kable("./output/meta_regression_incl_outlier_NEW_FEB24.html")
```
