---
title: "Descriptives"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
rm(list = ls())
library(dplyr)
library(tidyverse)
library(labelled)
library(ggplot2)
library(questionr)
library(psych)
#library(plyr)
```



```{r}
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/issptotal.Rdata")
#THE TOTAL MEANS FILE IS NOT SAVED, SO TO MAKE THE PLOTS I HAVE TO RUN THIS CODE FIRST

#This copy file has no missings (listwise deletion) so that I can calculate all the means with a constant N. 
issptotal$growharm[issptotal$growharm==88] <- 0
issptotal$growharm[is.na(issptotal$growharm)] <- 0
issptotal$pop_support[issptotal$pop_support==88] <- 0
issptotal$pop_support[is.na(issptotal$pop_support)] <- 0
issptotal$moreimp[is.na(issptotal$moreimp)] <- 0
issptotal$exag[is.na(issptotal$exag)] <- 0
issptotal$othersame[is.na(issptotal$othersame)] <- 0
issptotal$country_effort[is.na(issptotal$country_effort)] <- 0

issptotal_copy <- issptotal[complete.cases(issptotal), ]

table(issptotal_copy$surveyyear, useNA = "always")
attributes(issptotal_copy$surveyyear)

# Group by mean of multiple columns.  
means <- issptotal_copy %>% group_by(surveyyear) %>% 
  summarise(mean_lifeharm=mean(lifeharm_r),
            mean_progharm= mean(progharm),
            mean_worry= mean(worry),
            mean_econprotect= mean(econprotect),
            mean_wprice= mean(willing_price_r),
            mean_wtax= mean(willing_tax_r),
            mean_wliving= mean(willing_living_r),
            mean_dodiff= mean(dodiff),
            mean_doright= mean(doright_r),
            mean_peopled= mean(people_decide),
            mean_busd= mean(bus_decide),
            mean_growharm= mean(growharm),
            mean_popsup= mean(pop_support),
            mean_moreimp= mean(moreimp),
            mean_othersame= mean(othersame),
            mean_exag= mean(exag),
            mean_countryef= mean(country_effort),
            .groups = 'drop') %>%
            as.data.frame()
  

issptotmeans <- merge(issptotal_copy, means, by= "surveyyear", all.x=T)

#Now see if I can get this in a plot. 

ggplot(issptotmeans, aes(x=surveyyear)) + 
  geom_line(aes(y = mean_wprice), color = "purple") + 
  geom_line(aes(y = mean_wtax), color="turquoise", linetype="twodash") +
  geom_line(aes(y = mean_wliving), color = "pink", linetype=2) +
  ggtitle ("Willingness to make changes 1993-2010") +
  coord_cartesian(xlim = c(1993,2010), ylim = c(0,5)) +
  guides(fill="legend") +
  labs(y="Mean score", x="Year of survey")

ggsave("willingness_changes.png")

ggplot(issptotmeans, aes(x=surveyyear)) + 
  geom_line(aes(y = mean_lifeharm), color = "purple") + 
  geom_line(aes(y = mean_progharm), color="turquoise", linetype=6) +
  geom_line(aes(y = mean_worry), color = "pink", linetype=2) +
  geom_line(aes(y = mean_econprotect), color = "black", linetype=4) +
  ggtitle ("Attitudes 1993-2010") +
  coord_cartesian(xlim = c(1993,2010), ylim = c(0,5)) +
  guides(fill="legend") +
  labs(y="Mean score", x="Year of survey") +
  theme_classic()

ggsave("attitudes_issp.png")

ggplot(issptotmeans, aes(x=surveyyear)) + 
  geom_line(aes(y = mean_dodiff), color = "purple") + 
  geom_line(aes(y = mean_doright), color="turquoise", linetype=6) +
  ggtitle ("Do what is right") +
  coord_cartesian(xlim = c(1993,2010), ylim = c(0,5)) +
  guides(fill="legend") +
  labs(y="Mean score", x="Year of survey") +
  theme_classic()

ggsave("dorightdiff_issp.png")
  
ggplot(issptotmeans, aes(x=surveyyear)) + 
  geom_line(aes(y = mean_peopled), color = "black") + 
  geom_line(aes(y = mean_busd), color="red", linetype=6) +
  ggtitle ("Responsibility people or businesses") +
  coord_cartesian(xlim = c(1993,2010), ylim = c(0,5)) +
  guides(fill="legend") +
  labs(y="Mean score", x="Year of survey") +
  theme_classic()

ggsave("responsible_issp.png", width = 4, height = 4)

ggplot(issptotmeans, aes(x=surveyyear)) + 
  geom_line(aes(y = mean_growharm), color = "black") + 
  geom_line(aes(y = mean_popsup), color="red", linetype=6) +
  geom_line(aes(y = mean_moreimp), color = "pink", linetype=2) +
  geom_line(aes(y = mean_othersame), color = "turquoise") +
  geom_line(aes(y = mean_exag), color = "blue", linetype=2) +
  geom_line(aes(y = mean_countryef), color = "orange", linetype=5) +
  ggtitle ("Attitudes 2000-2010") +
  coord_cartesian(xlim = c(2000,2010), ylim = c(0,5)) +
  guides(fill="legend") +
  labs(y="Mean score", x="Year of survey") +
  theme_classic()

ggsave("attitudes2000_issp.png", width = 4, height = 4)

```


```{r}
#Let's look at trends in the EVS
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/evssel.Rdata")

means <- evssel %>% group_by(S020) %>% 
  summarise(mean_climate=mean(climate5, na.rm=T),
            .groups = 'drop') %>%
            as.data.frame()

evssel <- merge(evssel, means, by= "S020")

ggplot(evssel, aes(x=S020)) + 
  geom_line(aes(y = mean_climate), color = "darkgreen") + 
  ggtitle ("Willingness to give part of income to reduce environmental pollution") +
  coord_cartesian(xlim = c(1990,2008), ylim = c(0,5)) +
  guides(fill="legend") +
  labs(y="Mean score", x="Year of survey")+
  theme_classic()

ggsave("graph_evs.png", width = 4, height = 4)

vars <- evssel %>% group_by(S020) %>% 
  summarise(var_climate=var(climate5, na.rm=T),
            .groups = 'drop') %>%
            as.data.frame()

evssel <- merge(evssel, vars, by= "S020")

ggplot(evssel, aes(x=S020)) + 
  geom_line(aes(y = var_climate), color = "darkgreen") + 
  ggtitle ("Variance willingness to give part of income to reduce environmental pollution") +
  coord_cartesian(xlim = c(1990,2008), ylim = c(0,2)) +
  guides(fill="legend") +
  labs(y="Variance", x="Year of survey")+
  theme_classic()

ggsave("vargraph_evs.png", width = 4, height = 4)

```

```{r}
#ESS
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/esstotal.Rdata")

means <- esstotal %>% group_by(surveyyear) %>% 
  summarise(mean_cause=mean(ccnthum, na.rm=T),
            mean_resp=mean(ccrdprsn_cat, na.rm=T),
            mean_worry=mean(wrclmch, na.rm=T),
            .groups = 'drop') %>%
            as.data.frame()

esstotal <- merge(esstotal, means, by= "surveyyear")

ggplot(esstotal, aes(x=surveyyear)) + 
  geom_line(aes(y = mean_cause), color = "darkgreen") + 
  geom_line(aes(y = mean_resp), color = "red") + 
  geom_line(aes(y = mean_worry), color = "black") + 
  ggtitle ("Cause, responsibility and worry") +
  coord_cartesian(xlim = c(2016, 2020), ylim = c(0,5)) +
  guides(fill="legend") +
  labs(y="Mean score", x="Year of survey")+
  theme_classic()

ggsave("graph_ess.png", width = 4, height = 4)

var <- esstotal %>% group_by(surveyyear) %>% 
  summarise(var_cause=var(ccnthum, na.rm=T),
            var_resp=var(ccrdprsn_cat, na.rm=T),
            var_worry=var(wrclmch, na.rm=T),
            .groups = 'drop') %>%
            as.data.frame()

esstotal <- merge(esstotal, var, by= "surveyyear")

ggplot(esstotal, aes(x=surveyyear)) + 
  geom_line(aes(y = var_cause), color = "darkgreen") + 
  geom_line(aes(y = var_resp), color = "red") + 
  geom_line(aes(y = var_worry), color = "black") + 
  ggtitle ("Variance cause, responsibility and worry") +
  coord_cartesian(xlim = c(2016, 2020), ylim = c(0,2)) +
  guides(fill="legend") +
  labs(y="Variance", x="Year of survey")+
  theme_classic()

ggsave("vargraph_ess.png", width = 4, height = 4)

```

```{r}
#Eurobarometer
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/eb_tot5.Rdata")

means <- eb_tot %>% group_by(surveyyear) %>% 
  summarise(mean_env_quallife=mean(env_quallife5, na.rm=T),
            mean_env_vs_ec=mean(env_vs_ec5, na.rm=T),
            mean_role_ind=mean(role_ind5, na.rm=T),
            mean_big_pol=mean(big_pol5, na.rm=T), #Deze klopt nog niet
            mean_eff_daily=mean(eff_daily5, na.rm=T),
            mean_buyprod=mean(buyprod5, na.rm=T),
            mean_pers_imp=mean(pers_imp5, na.rm=T),
            mean_cc_unstop=mean(cc_unstop5, na.rm=T),
            mean_cc_exag=mean(cc_exag5, na.rm=T),
            mean_cc_prsact=mean(cc_prsact5, na.rm=T),
            mean_cc_poseu=mean(cc_poseu5, na.rm=T),
            mean_cc_unstop=mean(cc_unstop5, na.rm=T),
            mean_ccpercept=mean(ccpercept5, na.rm=T),
            mean_cchange=mean(cchange5, na.rm=T),
            mean_doprot_natgov=mean(doprot_natgov5, na.rm=T),
            mean_doprot_eu=mean(doprot_eu5, na.rm=T),
            mean_doprot_region=mean(doprot_region5, na.rm=T),
            mean_doprot_comp=mean(doprot_comp5, na.rm=T),
            mean_doprot_citiz=mean(doprot_citiz5, na.rm=T),
            mean_doprot_city=mean(doprot_city5, na.rm=T),
            mean_envp_eg=mean(envp_eg5, na.rm=T),
            mean_effr_eg=mean(effr_eg5, na.rm=T),
            mean_cchange2=mean(cchange2_5, na.rm=T),
            mean_cchangetot=mean(cchangetot5, na.rm=T),
            mean_prsaction=mean(prsaction5, na.rm=T),
            .groups = 'drop') %>%
            as.data.frame()

eb_tot <- merge(eb_tot, means, by= "surveyyear")

#Not sorted in a right way, try out!!!
ggplot(eb_tot, aes(x=surveyyear)) + 
  geom_line(aes(y = mean_cchange), color = "darkgreen") + 
  geom_line(aes(y = mean_ccpercept), color = "red") + 
  ggtitle ("Try") +
  coord_cartesian(xlim = c(2015, 2022), ylim = c(0,5)) +
  guides(fill="legend") +
  labs(y="Mean", x="Year of survey")+
  theme_classic()


```


