---
title: "Untitled"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---
# weighed gamlss , indep var

```{r}
rm(list=ls())
library(meta)
library(metafor)
library(here)
library(dplyr)
here()
here::i_am("scripts/analysis/meta_analysis_gamlss_weigh.Rmd")
```

```{r}
load(here("./data/meta_analysis", "total_indep_var_results_new.RData"))
load("/Users/anuschka/Documents/climatechange/climatechange/data/meta_analysis/total_indep_var_results_new.RData")

# Effects of mu's 
# Gender 
gender_gen <- metagen(TE = mu_sex_est,
                 seTE = mu_sex_sd,
                 data = total_indep_var_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(gender_gen)

# Age 
age_gen <- metagen(TE = mu_age_est,
                 seTE = mu_age_sd,
                 data = total_indep_var_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(age_gen)

# Educational level. This is now a dummy so how do i have to do this?
edu_med_gen <- metagen(TE = mu_isced_med_est,
                 seTE = mu_isced_med_sd,
                 data = total_indep_var_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(edu_med_gen)

edu_high_gen <- metagen(TE = mu_isced_high_est,
                 seTE = mu_isced_high_sd,
                 data = total_indep_var_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(edu_high_gen)

# Now for variance
# Gender
gender_var_gen <- metagen(TE = sig_sex_est,
                 seTE = sig_sex_sd,
                 data = total_indep_var_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(gender_var_gen)

# Age
age_var_gen <- metagen(TE = sig_age_est,
                 seTE = sig_age_sd,
                 data = total_indep_var_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(age_var_gen)

# Education

edu_var_med_gen <- metagen(TE = sig_isced_med_est,
                 seTE = sig_isced_med_sd,
                 data = total_indep_var_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(edu_var_med_gen)

edu_var_high_gen <- metagen(TE = sig_isced_high_est,
                 seTE = sig_isced_high_sd,
                 data = total_indep_var_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(edu_var_high_gen)

# Effects of first year on these effects
load("/Users/anuschka/Documents/climatechange/climatechange/data/meta_analysis/total_reg_results_gam_w_new.RData")
year <- total_reg_results %>% dplyr::select(mean_year, dep_var)
total_indep_var_results <- left_join(total_indep_var_results, year)

gender_year  <- metareg(gender_gen, ~ total_indep_var_results$mean_year)
summary(gender_year)

age_year  <- metareg(age_gen, ~ total_indep_var_results$mean_year)
summary(age_year)

edu_med_year  <- metareg(edu_med_gen, ~ total_indep_var_results$mean_year)
summary(edu_med_year)

edu_high_year  <- metareg(edu_high_gen, ~ total_indep_var_results$mean_year)
summary(edu_high_year)

# Variance
gender_year_v  <- metareg(gender_var_gen, ~ total_indep_var_results$mean_year)
summary(gender_year_v)

age_year_v  <- metareg(age_var_gen, ~ total_indep_var_results$mean_year)
summary(age_year_v)

edu_med_year_v  <- metareg(edu_var_med_gen, ~ total_indep_var_results$mean_year)
summary(edu_med_year_v)

edu_high_year_v  <- metareg(edu_var_high_gen, ~ total_indep_var_results$mean_year)
summary(edu_high_year_v)

```

```{r}
#Prepare data to make a kable table
mu_pool_indep <- data.frame(matrix(ncol = 4, nrow = 4))
colnames(mu_pool_indep) <- c("mu_sigma_1", "variable_1", "pooled_1", "p_1")

mu_pool_indep$variable_1 <- c("Gender", "Age", "Isced intermediate (ref=basic)", "Isced advanced (ref=basic)")
mu_pool_indep$mu_sigma_1 <- c("Mu", "", "", "")
mu_pool_indep$pooled_1 <- c(gender_gen$TE.random, age_gen$TE.random, edu_med_gen$TE.random, edu_high_gen$TE.random)
mu_pool_indep$p_1 <- c(gender_gen$pval.random, age_gen$pval.random, edu_med_gen$pval.random, edu_high_gen$pval.random)

gender_gen$statistic.random # t of HK (random effects model)
gender_gen$TE.random #effect size
gender_gen$pval.random # p value

# For the variance
sigma_pool_indep <- data.frame(matrix(ncol = 4, nrow = 4))
colnames(sigma_pool_indep) <- c("mu_sigma_1", "variable_1", "pooled_1", "p_1")

sigma_pool_indep$variable_1 <- c("Gender", "Age", "Isced intermediate (ref=basic)", "Isced advanced (ref=basic)")
sigma_pool_indep$mu_sigma_1 <- c("Sigma", "", "", "")
sigma_pool_indep$pooled_1 <- c(gender_var_gen$TE.random, age_var_gen$TE.random, edu_var_med_gen$TE.random, edu_var_high_gen$TE.random)
sigma_pool_indep$p_1 <- c(gender_var_gen$pval.random, age_var_gen$pval.random, edu_var_med_gen$pval.random, edu_var_high_gen$pval.random)

# The second part of the table consists of the estimates, standard error and p value of the mean year effect on the independent variables 
mu_my <- data.frame(matrix(ncol = 5, nrow = 4))
colnames(mu_my) <- c("mu_sigma_2", "variable_2", "estimate", "se", "p_2")
mu_my$variable_2 <- c("Gender", "Age", "Isced intermediate (ref=basic)", "Isced advanced (ref=basic)")
mu_my$mu_sigma_2 <- c("Mu", "", "", "")
mu_my$estimate <- c(as.numeric(gender_year$b[[2]]), as.numeric(age_year$b[[2]]), as.numeric(edu_med_year$b[[2]]), as.numeric(edu_high_year$b[[2]]))
mu_my$se <- c(gender_year$se[[2]], age_year$se[[2]], edu_med_year$b[[2]], edu_high_year$b[[2]])
mu_my$p_2 <- c(gender_year$pval[[2]], age_year$pval[[2]], edu_med_year$pval[[2]], edu_high_year$pval[[2]])

#The same for the variance of course
sigma_my <- data.frame(matrix(ncol = 5, nrow = 4))
colnames(sigma_my) <- c("mu_sigma_2", "variable_2", "estimate", "se", "p_2")
sigma_my$variable_2 <- c("Gender", "Age", "Isced intermediate (ref=basic)", "Isced advanced (ref=basic)")
sigma_my$mu_sigma_2 <- c("Sigma", "", "", "")
sigma_my$estimate <- c(as.numeric(gender_year_v$b[[2]]), as.numeric(age_year_v$b[[2]]), as.numeric(edu_med_year_v$b[[2]]), as.numeric(edu_high_year_v$b[[2]]))
sigma_my$se <- c(gender_year_v$se[[2]], age_year_v$se[[2]], edu_med_year_v$b[[2]], edu_high_year_v$b[[2]])
sigma_my$p_2 <- c(gender_year_v$pval[[2]], age_year_v$pval[[2]], edu_med_year_v$pval[[2]], edu_high_year_v$pval[[2]])

```




```{r}
# Do the same for the interaction effects (age, sex, isced and time)
load("/Users/anuschka/Documents/climatechange/climatechange/data/meta_analysis/total_inter_results_new.RData")

# Effects of mu's 
# Gender 
gender_inter_gen <- metagen(TE = mu_sex_est,
                 seTE = mu_sex_sd,
                 data = total_inter_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(gender_inter_gen)

# Age 
age_inter_gen <- metagen(TE = mu_age_est,
                 seTE = mu_age_sd,
                 data = total_inter_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(age_inter_gen)

# Educational level
edu_med_inter_gen <- metagen(TE = mu_isced_med_est,
                 seTE = mu_isced_med_sd,
                 data = total_inter_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(edu_med_inter_gen)

edu_high_inter_gen <- metagen(TE = mu_isced_high_est,
                 seTE = mu_isced_high_sd,
                 data = total_inter_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(edu_high_inter_gen)

# Now for variance
# Gender
gender_var_inter_gen <- metagen(TE = sig_sex_est,
                 seTE = sig_sex_sd,
                 data = total_inter_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(gender_var_inter_gen)

# Age
age_var_inter_gen <- metagen(TE = sig_age_est,
                 seTE = sig_age_sd,
                 data = total_inter_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(age_var_inter_gen)

# Education

edu_var_med_inter_gen <- metagen(TE = sig_isced_med_est,
                 seTE = sig_isced_med_sd,
                 data = total_inter_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(edu_var_med_inter_gen)

edu_var_high_inter_gen <- metagen(TE = sig_isced_high_est,
                 seTE = sig_isced_high_sd,
                 data = total_inter_results,
                 fixed = FALSE,
                 random = TRUE,
                 method.tau = "REML",
                 hakn = TRUE)

summary(edu_var_high_inter_gen)

```

```{r}
# Collect the input from this as well, to put in the table
mu_pool_inter <- data.frame(matrix(ncol = 4, nrow = 4))
colnames(mu_pool_inter) <- c("mu_sigma_3", "variable_3", "pooled_2", "p_3")
mu_pool_inter$variable_3 <- c("Gender", "Age", "Isced intermediate (ref=basic)", "Isced advanced (ref=basic)")
mu_pool_inter$mu_sigma_3 <- c("Mu", "", "", "")
mu_pool_inter$pooled_2 <- c(gender_inter_gen$TE.random, age_inter_gen$TE.random, edu_med_inter_gen$TE.random, edu_high_inter_gen$TE.random)
mu_pool_inter$p_3 <- c(gender_inter_gen$pval.random, age_inter_gen$pval.random, edu_med_inter_gen$pval.random, edu_high_inter_gen$pval.random)

# For the variance
sigma_pool_inter <- data.frame(matrix(ncol = 4, nrow = 4))
colnames(sigma_pool_inter) <- c("mu_sigma_3", "variable_3", "pooled_2", "p_3")
sigma_pool_inter$variable_3 <- c("Gender", "Age", "Isced intermediate (ref=basic)", "Isced advanced (ref=basic)")
sigma_pool_inter$mu_sigma_3 <- c("Sigma", "", "", "")
sigma_pool_inter$pooled_2 <- c(gender_var_inter_gen$TE.random, age_var_inter_gen$TE.random, edu_var_med_inter_gen$TE.random, edu_var_high_inter_gen$TE.random)
sigma_pool_inter$p_3 <- c(gender_var_inter_gen$pval.random, age_var_inter_gen$pval.random, edu_var_med_inter_gen$pval.random, edu_var_high_inter_gen$pval.random)


#Bind all the mean attitudes results
mean_indep <- cbind(mu_pool_indep, mu_my, mu_pool_inter)
sigma_indep <- cbind(sigma_pool_indep, sigma_my, sigma_pool_inter)
indep_total <- rbind(mean_indep, sigma_indep)

#Make stars of the p-values
indep_total$p_text_1 <- case_when(
indep_total$p_1 >= 0.05 ~ "",
indep_total$p_1 < 0.001 ~ "***",
indep_total$p_1 < 0.01 ~ "**",
indep_total$p_1 < 0.05 ~ "*"
)

indep_total$p_text_2 <- case_when(
indep_total$p_2 >= 0.05 ~ "",
indep_total$p_2 < 0.001 ~ "***",
indep_total$p_2 < 0.01 ~ "**",
indep_total$p_2 < 0.05 ~ "*"
)

indep_total$p_text_3 <- case_when(
indep_total$p_3 >= 0.05 ~ "",
indep_total$p_3 < 0.001 ~ "***",
indep_total$p_3 < 0.01 ~ "**",
indep_total$p_3 < 0.05 ~ "*"
)

#Select only the variables that I want to present in the table
indep_total <- dplyr::select(indep_total, mu_sigma_1, variable_1, pooled_1, p_text_1, estimate, se, p_text_2, pooled_2, p_text_3)

```


```{r}
options(knitr.kable.NA = '')
```

```{r}
kable(indep_total, digits = 3, caption = "Table 4. Effects of independent variables on climate change attitudes and polarization", 
      col.names = c( "", "Variables", "Pooled effect", "", "Estimate", "Std. Error", "", "Pooled effect", "")) %>%
  kable_classic_2(html_font = "Times", fixed_thead = T, full_width = F) %>%
  add_header_above(c(" " = 2, "Effects indep vars" = 2, "Mean year on indep vars" = 3, "Effects interaction" = 2), align = "c") %>%
   footnote(
    general_title = "Note.",
    general = "*** = p < 0.001, ** = p < 0.01, * = p < 0.05",
    threeparttable = TRUE,
    footnote_as_chunk = TRUE
    )%>%
    save_kable("/Users/anuschka/Documents/climatechange/climatechange/output/indep_var_table.png")
```





