---
title: "Untitled"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
rm(list = ls())
install.packages("gamlss")
library(gamlss)

```

```{r}
#install.packages("here")
library(here)
here()
here::i_am("scripts/analysis/single_regression.Rmd")
load(here("data", "dpes2021sel.RData")) 
```

```{r}
# I want to have a regression where both the intercept and the variance are also stored in some list/df. 


set.seed(23)

predictors <- c("sex", "urban", "educ_cat", "lroverall_mean")
fit_list <- list()
for (i in c("cchange_prob", "cc_measures", "cc_cause")) {
  fit_list[[i]] <- lm(as.formula(paste(i, "~", paste(predictors, collapse = " + "))), data = dpes2021sel)
}





# First I have to make a dataframe where I would like to save the results of the regression. From the regression, I want to keep the intercept and the variance. In the end, I want to have way more information in that dataset that I want to use for my meta-regression, but I think I should not already include that here. 
results_reg_dpes <- data.frame(dependent_variable = character(),
                        intercept = numeric(),
                        std_dev = numeric(), 
                        variance = numeric())

# Define the predictor variables, now as a test, but have to include more predictor variables. And could I maybe store in the results dataframe how many predictors I have used? 
predictors <- c("sex", "urban", "educ_cat", "lroverall_mean")

# Loop through the different dependent variables I have in my dataset of NKO, and then perform a linear regression on each of these dep vars by the predictors I have defined above. 
for (dependent_variable in c("cchange_prob", "cc_measures", "cc_cause")) {
  
  # Perform the linear regression. Collapse + means that it puts a + sign between each of the predictors (as a normal regression would look like)
  fit <- lm(as.formula(paste(dependent_variable, "~", paste(predictors, collapse = " + "))), data = dpes2021sel)
  
  # Extract the intercept and variance of the residuals
  intercept <- coef(fit)[1]
  std_dev <- sd(residuals(fit))
  variance <- var(residuals(fit))
  
  # Add the results to the dataframe created above
  results_reg_dpes <- rbind(results_reg_dpes, data.frame(dependent_variable, intercept, std_dev, variance))
}

#Include more meta-information to this results dataset
results_reg_dpes$data_coll_procedure <- 3 
results_reg_dpes$meas_education <- 1 
results_reg_dpes$meas_religion <- 0
results_reg_dpes$meas_lr <- 1 
results_reg_dpes$surveyyear <- 2021

#Save this 
save(results_reg_dpes, file = "/Users/anuschka/Documents/climatechange/climatechange/data/meta_analysis/results_reg_dpes.RData")

# Let's try it again with another dataset. 

load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/esstotal.RData")

# In this dataset I have 2 waves included. So I either have to split this by year, or run it seperately per dataset.
# Split the dataframe by survey year
split_ess <- split(esstotal, esstotal$surveyyear)

# Initialize a dataframe to store the results
results_reg_ess <- data.frame(surveyyear = numeric(),
                        dependent_variable = character(),
                        intercept = numeric(),
                        variance = numeric(), 
                        std_dev = numeric())

#Deze uitprobeersels gaan later weg ##############
for (i in 1:length(split_ess)) {
  print(split_ess[[i]])
}

year_data <- as.data.frame(split_ess[2])
names(year_data) <- names(esstotal)

length(split_ess)

split_ess[2]
surveyyear <- split_ess[i]
##################################################

# Define the predictor variables
predictors <- c("sex", "eduyrs", "urban", "ch_attend", "income", "agea", "lrscale")

# Loop through each survey year
for (i in 1:length(split_ess)) {
  
  # Get the data for the current survey year
  year_data <- as.data.frame(split_ess[i])
  names(year_data) <- names(esstotal)
  
  
  # Loop through each dependent variable
  for (dependent_variable in c("worry", "cause", "pers_resp")) {
  
    # Perform the linear regression
    fit <- lm(as.formula(paste(dependent_variable, "~", paste(predictors, collapse = " + "))), data = year_data)
  
    # Extract the intercept and variance of the residuals
    intercept <- coef(fit)[1]
    variance <- var(residuals(fit))
    std_dev <- sd(residuals(fit))
  
    # Add the results to the dataframe
    results_reg_ess <- rbind(results_reg_ess, data.frame(
                                              dependent_variable, 
                                              intercept, 
                                              variance, std_dev))
  }
}

#Het enige wat nu nog mist is dat hij ook het jaar opslaat in de dataframe

results_reg_ess$data_coll_procedure <- 3 
results_reg_ess$meas_education <- 0
results_reg_ess$meas_religion <- 1
results_reg_ess$meas_lr <- 0
results_reg_ess$surveyyear <- c(2016, 2016, 2016, 2020, 2020, 2020)

save(results_reg_ess, file = "/Users/anuschka/Documents/climatechange/climatechange/data/meta_analysis/results_reg_ess.RData")

#Look if I can do ISSP as well (is larger)
```


```{r}
load(here("data", "issptotal.RData"))

split_issp <- split(issptotal, issptotal$surveyyear)

predictors <- c("sex", "eduyrs", "urban", "ch_attend", "income", "age", "lrscale")
predictors <- c("sex", "eduyrs", "urban", "ch_attend")

head(issptotal$income)

# Define the predictor variables
predictors <- c("sex", "eduyrs")
deps <- c("worry","lifeharm")

fitissp_list <- list()

# Loop through each survey year
for (i in 1:length(split_issp)) {
  tmp <- list()
  # Loop through each dependent variable
  for (j in 1:length(deps)) {
  # Perform the linear regression
  tmp[[j]] <- lm(as.formula(paste(deps[j], "~", paste(predictors, collapse = " + "))), data = split_issp[[i]])
  }
  fitissp_list[[i]] <- tmp
}

# I get this error: Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
# contrasts can be applied only to factors with 2 or more levels
sapply(lapply(split_issp, unique), length)
sapply(lapply(issptotal, unique), length)
#But all my variables have more than 1 level...

```


```{r}
summary(fit_list[[1]])

hist(fit_list[[1]]$residuals)

load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/issptotal.RData")

test <- data.frame(issptotal$worry, issptotal$eduyrs, issptotal$surveyyear)
test <- na.omit(test)
names(test) <- c("worry", "eduyrs", "surveyyear")

summary(lm(worry ~ 1 + eduyrs, data=test))

gamlss(worry ~ 1 + eduyrs,  sigma.formula = ~ 1 + eduyrs,  data = test,    family = NO)


split_test <- split(test, test$surveyyear)

predictors <- c("sex", "eduyrs", "urban", "ch_attend", "income", "age", "lrscale")
predictors <- c("sex", "eduyrs", "urban", "ch_attend")

head(issptotal$income)

# Define the predictor variables
predictors <- c("eduyrs")
deps <- c("worry")

test_list <- list()

# Loop through each survey year
for (i in 1:length(split_test)) {
  tmp <- list()
  # Loop through each dependent variable
  for (j in 1:length(deps)) {
  # Perform the linear regression
  tmp[[j]] <- lm(as.formula(paste(deps[j], "~", paste(predictors, collapse = " + "))), data = split_test[[i]])
  }
  test_list[[i]] <- tmp
} 


gamlss(worry ~ 1 + eduyrs,  sigma.formula = ~ 1 + eduyrs,  data = test,    family = NO)


                                                                                                   




                                                                                                
                                                                                                   
                                                                                                                                          
                                                                                                   

```

