---
title: "Data preparation left-right placement expert data"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(eval = FALSE)
options(width = 100)
colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

In this script, I recode expert data of CHES and POPPA to be able to use as a substitute for left-right placement of the I&O research data. In the end, I have not used this variable in my thesis, but I still refer to it in the script for I&O research and it can still be used in a later stadium (to include political placement).

```{r}
#Load the data of poppa
pop <- read_dta("/Users/anuschka/Documents/gesis_dir/poppa/expert_data_stata.dta")

#Select only the Netherlands and general left-right placement
popsel <- pop %>% filter(country_id==19) %>%
  select(nr_experts, party, lroverall) %>%
  dplyr::rename(party_name = party) 

popsel$party_name <- revalue(popsel$party_name, c("50Plus"= "50PLUS"))

#Do the same for the CHES data
ches <- read_dta("/Users/anuschka/Documents/gesis_dir/ches/ches2019.dta")
dutch <- 1001:1051  #Dutch party ids
ches <- ches[ches$party_id %in% dutch, ] 

ches <- ches %>% select(party, party_name, lrgen) 
ches$party_name <- revalue(ches$party_name, c("PVdD" = "PvdD"))

names(ches) <- names(popsel) #namen gelijk maken

#Combine the two
expert <- rbind(ches, popsel)
expert <- na.omit(expert)

# Calculate the mean left-right placement of these columns of experts
expert2 <- expert %>% #Maar deze wel
  group_by(party_name) %>%
  summarise_at(vars(lroverall), list(lroverall_mean = mean), na.rm=T) 

save(expert, file = "/Users/anuschka/Documents/climatechange/climatechange/data/all_waves/expert.RData")

# Test it on a dataset that later on was no longer part of my thesis
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/dpes2021sel.RData")

unique(dpes2021sel$party_name)

dpes2021sel$party_name <- as.character(dpes2021sel$party_name)
unique(dpes2021sel$party_name2)
unique(expert2$party_name)

dpes2021sel %>% 
  left_join(expert2, by="party_name") -> dpes2021seltest

save(expert2, file = "/Users/anuschka/Documents/climatechange/climatechange/data/all_waves/expert.RData")
```

