---
title: "dataprepIII"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

In this script, I recode variables once again to standardize them across the different datasets. 
```{r}

rm(list = ls())
library(haven)
library(dplyr)
library(foreign)
library(tidyverse)
library(labelled)
library(ggplot2)
library(questionr)
library(psych)
library(plyr)

```

```{r}
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/eb_tot.Rdata")

#Collect data on religion (because didn't include that everywhere for EB)
eb1982 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/eurobarometer/eb1982.sav", use.value.labels = T,  to.data.frame = T)

look_for(eb1982, "religious")

relsel <- eb1982 %>% filter(v5=="NETHERLANDS") %>%
              select(v1, v53)

table(relsel$v53, useNA = "always")
relsel$religion <- as.numeric(relsel$v53)
relsel$religion[is.na(relsel$religion)] <- 88
relsel$religion <- as.factor(relsel$religion)
levels(relsel$religion) <- c("Religious", "Not religious", "Atheist", "Missing")

look_for(eb1986, "attendance")

rel86 <- eb1986 %>% filter(v5=="NETHERLANDS") %>%
  select(v1, v281)

table(rel86$v281, useNA = "always") #15 missings on religion. 
rel86$v281 <- as.numeric(rel86$v281)
mean(rel86$v281, na.rm = T)
rel86$v281[is.na(rel86$v281)] <- 4.794118 #High score means very religious.

relsel = subset(relsel, select = -c(v53) )
relsel <- plyr::rbind.fill(relsel, rel86)

look_for(eb1992, "church")

rel92 <- eb1992 %>% filter(v5=="NETHERLANDS") %>%
      select(v1, v647, v648)
table(rel92$v647, useNA = "always") #488 missings on this variable
rel92$v647 <- as.numeric(rel92$v647)
rel92$attend[rel92$v647==1] <- 5
rel92$attend[rel92$v647==2] <- 4
rel92$attend[rel92$v647==3] <- 3
rel92$attend[rel92$v647==4] <- 2
rel92$attend[rel92$v647==5] <- 1
table(rel92$attend, useNA = "always")

table(rel92$v648, useNA = "always") #Religion has 77 missings. But I notice that answer cats differ over the years. To compare with the other years, I will create one cat agnost/atheist
rel92$v648 <- as.numeric(rel92$v648)
rel92$religion <- NA
rel92$religion[rel92$v648==1] <- 1
rel92$religion[rel92$v648==2] <- 2
rel92$religion[rel92$v648==3 | rel92$v648==4] <- 3
rel92$religion[is.na(rel92$religion)] <- 88
rel92$religion <- as.factor(rel92$religion)
levels(rel92$religion) <- c("Religious", "Not religious", "Agnost/Atheist", "Missing")

rel92 = subset(rel92, select = -c(v647, v648) )
relsel <- plyr::rbind.fill(relsel, rel92)

save(relsel, file = "./data/all_waves/relsel.RData")
#In the years after 1992 nothing with regard to religion was asked.

```

```{r}
#Recode the dependent variables to all have a scale from 1 to 5. 

table(eb_tot$env_ec_stat, useNA = "always")
eb_tot$env_ec_stat5 <- (eb_tot$env_ec_stat-1)*(4/2)+1
table(eb_tot$env_prsimp, useNA = "always")
eb_tot$env_prsimp5 <- (eb_tot$env_prsimp-1)*(4/2)+1
table(eb_tot$env_quallife, useNA = "always")
eb_tot$env_quallife5 <- (eb_tot$env_quallife-1)*(4/3)+1
table(eb_tot$env_vs_ec, useNA = "always")
eb_tot$env_vs_ec5 <- (eb_tot$env_vs_ec-1)*(4/1)+1
table(eb_tot$role_ind, useNA = "always")
eb_tot$role_ind5 <- (eb_tot$role_ind-1)*(4/3)+1
table(eb_tot$big_pol, useNA = "always")
eb_tot$big_pol5 <- (eb_tot$big_pol-1)*(4/3)+1
table(eb_tot$eff_daily, useNA = "always")
eb_tot$eff_daily5 <- (eb_tot$eff_daily-1)*(4/3)+1
table(eb_tot$buyprod, useNA = "always")
eb_tot$buyprod5 <- (eb_tot$buyprod-1)*(4/3)+1
table(eb_tot$pers_imp, useNA = "always")
eb_tot$pers_imp5 <- (eb_tot$pers_imp-1)*(4/3)+1
table(eb_tot$cc_unstop, useNA = "always")
eb_tot$cc_unstop5 <- (eb_tot$cc_unstop-1)*(4/3)+1
table(eb_tot$cc_exag, useNA = "always")
eb_tot$cc_exag5 <- (eb_tot$cc_exag-1)*(4/3)+1
table(eb_tot$cc_poseu, useNA = "always")
eb_tot$cc_poseu5 <- (eb_tot$cc_poseu-1)*(4/3)+1
table(eb_tot$cc_prsact, useNA = "always")
eb_tot$cc_prsact5 <- (eb_tot$cc_prsact-1)*(4/3)+1
table(eb_tot$ccpercept, useNA = "always") 
eb_tot$ccpercept[eb_tot$ccpercept=="1  Not a serious problem at all"] <- 1
eb_tot$ccpercept[eb_tot$ccpercept=="10  An extremely serious problem"] <- 10
eb_tot$ccperceptn <- as.numeric(eb_tot$ccpercept) 
table(eb_tot$ccpercept5, useNA = "always")
eb_tot$ccpercept5 <- (eb_tot$ccperceptn-1)*(4/9)+1
table(eb_tot$cchange, useNA = "always")
eb_tot$cchange[eb_tot$cchange=="Mentioned"] <- 1
eb_tot$cchange[eb_tot$cchange=="Not mentioned"] <- 0
eb_tot$cchange <- as.numeric(eb_tot$cchange)
eb_tot$cchange5 <- eb_tot$cchange*(4/1)+1
table(eb_tot$doprot_natgov, useNA="always")
eb_tot$doprot_natgov5 <- (eb_tot$doprot_natgov-1)*(4/2)+1
table(eb_tot$doprot_eu, useNA="always")
eb_tot$doprot_eu <- as.numeric(eb_tot$doprot_eu)
eb_tot$doprot_eu5 <- (eb_tot$doprot_eu-1)*(4/2)+1
table(eb_tot$doprot_region, useNA="always")
eb_tot$doprot_region <- as.numeric(eb_tot$doprot_region)
eb_tot$doprot_region5 <- (eb_tot$doprot_region-1)*(4/2)+1
table(eb_tot$doprot_comp, useNA="always")
eb_tot$doprot_comp <- as.numeric(eb_tot$doprot_comp)
eb_tot$doprot_comp5 <- (eb_tot$doprot_comp-1)*(4/2)+1
table(eb_tot$doprot_citiz, useNA="always")
eb_tot$doprot_citiz <- as.numeric(eb_tot$doprot_citiz)
eb_tot$doprot_citiz5 <- (eb_tot$doprot_citiz-1)*(4/2)+1
table(eb_tot$doprot_city, useNA="always")
eb_tot$doprot_city <- as.numeric(eb_tot$doprot_city)
eb_tot$doprot_city5 <- (eb_tot$doprot_city-1)*(4/2)+1
table(eb_tot$envp_eg, useNA="always")
eb_tot$envp_eg5 <- (eb_tot$envp_eg-1)*(4/3)+1
table(eb_tot$effr_eg, useNA="always")
eb_tot$effr_eg5 <- (eb_tot$effr_eg-1)*(4/3)+1
table(eb_tot$cchange2, useNA="always")
eb_tot$cchange2_5 <- (eb_tot$cchange2-1)*(4/1)+1
table(eb_tot$cchangetot5, useNA="always")
eb_tot$cchangetot5 <- (eb_tot$cchangetot-1)*(4/1)+1
table(eb_tot$prsaction5, useNA="always")
eb_tot$prsaction5 <- (eb_tot$prsaction-1)*(4/1)+1

#I see that for 2017, bigpol has no _, so it has created 2 variables. I want to merge the 2 but dont know how. Everything below does not work
table(eb_tot$bigpol, useNA = "always")
eb_tot$bigpol5 <- (eb_tot$bigpol-1)*(4/3)+1
eb_tot$big_pol5[studyno1="2"] <- eb_tot$bigpol5
eb_tot <- rbind(eb_tot$big_pol5, eb_tot$big_pol)

bigpol <- eb_tot %>% select(studyno1, bigpol5)
bigpol <- bigpol %>% dplyr::rename(big_pol5 = bigpol5)
eb_tot <- plyr::rbind.fill(eb_tot, bigpol)

save(eb_tot, file = "/Users/anuschka/Documents/climatechange/climatechange//data/final_data/eb_tot5.RData")
load("/Users/anuschka/Documents/climatechange/climatechange//data/final_data/eb_tot5.RData")
```


```{r}
#Now that all dependent variables are coded the same way, I have to code the independent variables in the same way as well

load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/eb_tot5.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/esstotal.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/issptotal.Rdata")
load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/evssel.Rdata")

16247 + 3151 + 3574 + 4933 #27905 total N

#Start with an easy one, gender
table(eb_tot$gender) #R has added score 3 and 4 to gender, although in the original datasets they're all coded with the same name
table(eb_tot$gender, eb_tot$surveyyear) #THis is the case in 1995 and 2015. 
eb_tot$gender[eb_tot$gender==3] <- "Man"
eb_tot$gender[eb_tot$gender==4] <- "Woman"
eb_tot$gender <- droplevels(eb_tot$gender)

table(esstotal$gndr, esstotal$surveyyear)
esstotal$gndr[esstotal$gndr==1] <- "Male"
esstotal$gndr[esstotal$gndr==2] <- "Female"
esstotal$gndr <- droplevels(esstotal$gndr)

table(evssel$X001)
evssel$X001 <- haven::as_factor(evssel$X001)
evssel$X001 <- droplevels(evssel$X001)

table(issptotal$sex, issptotal$surveyyear)
issptotal$sex[issptotal$sex==1] <- "Male"
issptotal$sex[issptotal$sex==2] <- "Female"
issptotal$sex <- droplevels(issptotal$sex)

#Turn around male/female to be in accordance with other datasets. THIS DOESN"T WORK
issptotal$gender <- as.numeric(issptotal$sex)
table(issptotal$gender)
issptotal$gender[issptotal$gender==2] <- 0
issptotal$gender[issptotal$gender==0] <- "Male"
issptotal$gender[issptotal$gender==1] <- "Female"
issptotal$gender <- as.factor(issptotal$gender)

save(eb_tot, file="/Users/anuschka/Documents/climatechange/climatechange/data/final_data/eb_tot5.Rdata")
save(esstotal, file="/Users/anuschka/Documents/climatechange/climatechange/data/final_data/esstotal.Rdata")
save(issptotal, file="/Users/anuschka/Documents/climatechange/climatechange/data/final_data/issptotal.Rdata")
save(evssel, file="/Users/anuschka/Documents/climatechange/climatechange/data/final_data/evssel.Rdata")

load("/Users/anuschka/Documents/climatechange/climatechange/data/final_data/eb_tot5.Rdata")

# Urbanity
table(eb_tot$urban, useNA = "always")
attributes(eb_tot$urban)
eb_tot$urban <- as.character(eb_tot$urban)
eb_tot$urban[eb_tot$urban=="RURAL AREA - VIL" | eb_tot$urban== "Rural area or village" | eb_tot$urban==  "Rural area-vilage"] <- 1 
eb_tot$urban[is.na(eb_tot$urban)] <- "Rural area or village"
eb_tot$urban[eb_tot$urban=="SM,MDL SZE TOWN" | eb_tot$urban== "Mid size town" | eb_tot$urban==  "Small or middle size town" | eb_tot$urban== "Small or middle sized town" | eb_tot$urban== "Small/middle town" | eb_tot$urban=="Small or medium-sized town"]  <- "Small or medium town"
eb_tot$urban[eb_tot$urban=="Big town" | eb_tot$urban== "BIG TOWN" | eb_tot$urban==  "Large town" | eb_tot$urban== "Large town/city"] <- "Large town"
eb_tot$urban <- as.factor(eb_tot$urban)
factor(eb_tot$urban, levels=c("Rural area or village", "Small or medium town", "Large town", "Missing"), ordered=TRUE)

table(esstotal$domicil, useNA = "always")
attributes(esstotal$domicil)
esstotal$domicil <- as.character(esstotal$domicil)
esstotal$domicil[esstotal$domicil==1 | esstotal$domicil=="A big city"] <- "Large town"
esstotal$domicil[esstotal$domicil==2 | esstotal$domicil==3 | esstotal$domicil=="Suburbs or outskirts of big city" | esstotal$domicil=="Town or small city"] <- "Small or medium town"
esstotal$domicil[esstotal$domicil==4 | esstotal$domicil==5 | esstotal$domicil=="Country village" | esstotal$domicil=="Farm or home in countryside"] <- "Rural area or village"
esstotal$domicil[is.na(esstotal$domicil)] <- "Missing"
esstotal$domicil <- as.factor(esstotal$domicil)
factor(esstotal$domicil, levels=c("Rural area or village", "Small or medium town", "Large town", "Missing"), ordered=TRUE)

table(issptotal$urbrur, useNA = "always")
attributes(issptotal$urbrur)
issptotal$urbrur[issptotal$urbrur==1] <- "Large town"
issptotal$urbrur[issptotal$urbrur==4 | issptotal$urbrur==5] <- "Rural area or village"
issptotal$urbrur[issptotal$urbrur==2] <- "Small or medium town" #------Hierna gaat het mis
ifelse(issptotal$urbrur==3 & issptotal$surveyyear==2010, issptotal$urbrur=="Small or medium town", issptotal$urbrur=="Rural area or village")


issptotal$urbrur[issptotal$urbrur[issptotal$surveyyear==2010]==3] <- "Small or medium town"



issptotal$urbrur[issptotal$urbrur[issptotal$surveyyear==2010]==2 | issptotal$urbrur[issptotal$surveyyear==1993]==2| 
 issptotal$urbrur[issptotal$surveyyear==2000]==2 | issptotal$urbrur[issptotal$surveyyear==2010]==3] <- "Small or medium town"

table(issptotal$urbrur[issptotal$surveyyear==2010]==3)

#Education 
freq(eb_tot$eduyrs)
eb_tot$edutest <- as.numeric(eb_tot$age) - as.numeric(eb_tot$eduyrs)
freq(eb_tot$edutest)
eb_tot$edutest[eb_tot$edutest < 0] <- NA #3148 missings
freq(esstotal$eduyrs)
table(esstotal$eduyrs, useNA = "always")
esstotal$edutest <- as.numeric(esstotal$agea) - as.numeric(esstotal$eduyrs)
esstotal$edutest[esstotal$edutest < 0] <- NA
freq(esstotal$edutest) # Here 268 people with an invalid score

freq(evssel$educ_mis)
evssel$eduyrs <- evssel$age_mis - evssel$educ_mis 
freq(evssel$eduyrs) #This value shouldn't be under 0, because that means you've studied longer than you lived. So everyone under 0 should get NA
evssel$eduyrs[evssel$eduyrs < 0] <- NA #124 persons have this score. The variable is now in accordance with the other datasets

freq(issptotal$age - issptotal$eduyrs) #53 people studied for 39 years and 90 for 40 years?
issptotal$edutest <- as.numeric(issptotal$age) - as.numeric(issptotal$eduyrs)
freq(issptotal$edutest) # Also a lot of people with a score below 0. 
issptotal$edutest[issptotal$edutest < 0] <- NA #459 people have this invalid score

# Left-right placement
table(esstotal$lrscale, useNA = "always")
table(evssel$lr_mis, useNA = "always")
table(issptotal$party_lr, useNA = "always")
# For issp, 6 means other and 7 no preference. So those are not the same. 
issptotal$lrscale <- issptotal$party_lr
issptotal$lrscale <- as.numeric(issptotal$lrscale)
issptotal$lrscale <- (issptotal$lrscale -1) * (9/4) + 1
table(issptotal$lrscale, useNA = "always")
eb_tot$bigpol5 <- (eb_tot$bigpol-1)*(4/3)+1
issptotal$lrscale[issptotal$lrscale ==12.25 | issptotal$lrscale ==14.5] <- 77 # Other or no preference
issptotal$lrscale[issptotal$lrscale ==196.75] <- 88
#And eurobarometer needs to be added here ------------------------------------

#Income
table(esstotal$hinctnta, useNA = "always") #This is household income on a scale from 1 to 10. 
table(evssel$X047_EVS, useNA = "always") #Scale of household incomes from 1 to 10 as well, with 540 missings. 
table(issptotal$nl_finc, issptotal$surveyyear, useNA = "always") #This is the household income after taxes. 
issptotal$nl_finc[issptotal$surveyyear==2000] <- as.numeric(as.character(issptotal$nl_finc))


```


