---
title: "Untitled"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
rm(list = ls())
library(foreign) #loads sav files into R, haven package is less useful with variable structure/type and recoding
library(haven)
library(tidyverse) 
library(plyr) 
library(dplyr)
library(questionr)
library(psych)
```

```{r}
dpes2021 <- foreign::read.spss("/Users/anuschka/Documents/gesis_dir/dpes/dpes2021.sav", use.value.labels = T,  to.data.frame = T)


#Select the individuals who participated in the pre-election survey
dpes2021sel <- dpes2021 %>% filter(V006_pre == "Yes") %>%
  select(RNR, Wght_Dem, Wght_CBS, V001, V010, V071, N91, V352, N92, V368, D005, V061, N44, N176)


#Dependent vars
table(dpes2021sel$V061, useNA = "always") #Most important national problem. One of the answer cats is environment, but it has about 703 missings. And is environment the same as climate change?
dpes2021sel$cchange_prob <-ifelse(dpes2021sel$V061=="Environment",1,0)
dpes2021sel$cchange_prob <- (dpes2021sel$cchange_prob)*(5/1)
dpes2021sel$cc_measures <- as.numeric(dpes2021sel$N44) #Also has 711 missings. 
dpes2021sel$cc_measures <- (dpes2021sel$cc_measures - 1)*(4/6)+1
table(dpes2021sel$N176, useNA = "always")
dpes2021sel$cc_cause <- as.numeric(dpes2021sel$N176)
dpes2021sel <- dpes2021sel %>% 
     mutate_at(c("cc_cause"), funs(recode(., `1` = 4, `2` = 3, `3` = 2, `4` = 1)))
dpes2021sel$cc_cause <- (dpes2021sel$cc_cause - 1)*(4/3)+1


#Independent vars recoding
dpes2021sel$sex <- revalue(dpes2021sel$V010, c("Male"="1", "Female"="2", "Other, namely" = NA))
dpes2021sel$sex <- droplevels(dpes2021sel$sex)
table(dpes2021sel$V071, useNA = "always") #Political party has 1064 missings
table(dpes2021sel$N91, useNA = "always")
dpes2021sel$ethnicity <- revalue(dpes2021sel$N91, c("Dutch background"="dutch", "First generation foreign, Western background"="western", "Second generation foreign, Western background"="western", "First generation foreign, non-Western background"="non-western","Second generation foreign, non-Western background" = "non-western"))
table(dpes2021sel$church_att, useNA = "always")
attributes(dpes2021sel$church_att)
dpes2021sel$ch_attend <- as.numeric(dpes2021sel$V352)
dpes2021sel <-  dpes2021sel %>%
     mutate_at(c("ch_attend"), funs(recode(., `1` = 5, `2` = 4, `3` = 3, `4` = 2, `5`= 1)))
dpes2021sel$ch_attend <- as.factor(dpes2021sel$ch_attend)
dpes2021sel$ch_attend <- revalue(dpes2021sel$ch_attend, c("1" = "almost never", "2" = "several times a year", "3"= "once a month", "4" = "2 or 3 times a month", "5" = "Once a week or more"))
table(dpes2021sel$N92, useNA = "always") #Income, how to recode this?
table(dpes2021sel$D005, useNA = "always") #Urbanity
dpes2021sel$urban <- revalue(dpes2021sel$D005, c("Very low - fewer than 500 addresses per square kilometer" = "low urbanity", "Low - 500 to 1,000 addresses per square kilometer" = "low urbanity", "Medium - 1,000 to 1,500 addresses per square kilometer" = "medium urbanity", "High - 500 to 2,000 addresses per square kilometer" = "high urbanity","Very high - 2,500 addresses or more per square kilometer" = "high urbanity"))
dpes2021sel$urban[is.na(dpes2021sel$urban)] <- "missing"
dpes2021sel$urban <- factor(dpes2021sel$urban, levels=c("low urbanity", "medium urbanity", "high urbanity", "missing"), ordered=TRUE)

dpes2021sel$educ_cat <- as.numeric(dpes2021sel$V368)
dpes2021sel <-  dpes2021sel %>%
     mutate_at(c("educ_cat"), funs(recode(., `1` = 1, `2` = 1, `3` = 1, `4` = 2, `5`= 2, `6` = 3, `7` = 3, `8` = 3)))
dpes2021sel$educ_cat[dpes2021sel$educ_cat==9] <- NA
dpes2021sel$educ_cat <- as.factor(dpes2021sel$educ_cat) 
dpes2021sel$educ_cat <- revalue(dpes2021sel$educ_cat, c("1" ="low", "2"="medium", "3"= "high"))

load("/Users/anuschka/Documents/climatechange/climatechange/data/all_waves/expert.RData")

dpes2021sel$party_name <- as.character(dpes2021sel$V071)
table(dpes2021sel$party_name)
dpes2021sel$party_name <- revalue(dpes2021sel$party_name, c("ChristenUnie"= "CU", "GroenLinks"="GL","Forum voor Democratie"="FvD"))

dpes2021sel %>% 
  left_join(expert2, by="party_name") -> dpes2021sel

dpes2021sel <-  dpes2021sel %>% select(RNR, V001, cchange_prob:lroverall_mean, N92)

save(dpes2021sel, file= "/Users/anuschka/Documents/climatechange/climatechange/data/final_data/dpes2021sel.RData")

```



NOG WEGHALEN

```{r}
pop <- read_dta("/Users/anuschka/Documents/gesis_dir/poppa/expert_data_stata.dta")

popsel <- pop %>% filter(country_id==19) %>%
      select(nr_experts, party, lroverall) %>%
      dplyr::rename(party_name = party) 

popsel$party_name <- revalue(popsel$party_name, c("50Plus"= "50PLUS"))

ches <- read_dta("/Users/anuschka/Documents/gesis_dir/ches/ches2019.dta")
dutch <- 1001:1051  #Dutch party ids
ches <- ches[ches$party_id %in% dutch, ] 

ches <- ches %>% select(party, party_name, lrgen) 
ches$party_name <- revalue(ches$party_name, c("PVdD" = "PvdD"))

expert <- merge(ches, popsel, by = "party_name", all.y = T)

save(expert, file = "/Users/anuschka/Documents/climatechange/climatechange/data/all_waves/expert.RData")

means <- expert %>%
  group_by(party_name) %>%
  summarise_at(vars(lrgen, lroverall), list(mean = mean), na.rm=T) 

expert <- merge(expert, means, by = "party_name", all = T)

expert$total_mean <- rowMeans(expert[ , c('lrgen_mean','lroverall_mean')], na.rm=T)

save(expert, file = "/Users/anuschka/Documents/climatechange/climatechange/data/all_waves/expert.RData")

#Now I would like to give individuals that voted for a party the score of the colmeans above. So I make sure the names are the same between the datasets. 

table(dpes2021sel$party_name, useNA = "always")
table(expert$party_name)
dpes2021sel$party_name <- dpes2021sel$V071
dpes2021sel$party_name <- revalue(dpes2021sel$V071, c("GroenLinks" = "GL", "ChristenUnie" = "CU", "Forum voor Democratie" = "FvD"))

expert_df <- as.data.frame(expert)

dpes2021seltest <- merge(dpes2021sel, expert)
dpes_unique <- unique(dpes2021seltest)
 



#Dividing in three cats left/middle/right. NOT NEEDED
expert$lr_cat <- NA
expert$lr_cat[expert$total_mean <= 4] <- 1
expert$lr_cat[expert$total_mean >4 & expert$total_mean <= 7] <- 2
expert$lr_cat[expert$total_mean > 7] <- 3 

```

